// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Deal.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Game.Protocal {

  /// <summary>Holder for reflection information generated from Deal.proto</summary>
  public static partial class DealReflection {

    #region Descriptor
    /// <summary>File descriptor for Deal.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DealReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpEZWFsLnByb3RvEg1HYW1lLlByb3RvY2FsGg9XYXJlaG91c2UucHJvdG8a",
            "DkVudW1UeXBlLnByb3RvIh8KDUNTQWR2U2tpcERlYWwSDgoGRGVhbElkGAEg",
            "ASgFIuoBCgxTQ0NyZWF0ZURlYWwSDgoGRGVhbElkGAEgASgFEhcKD0RlYWxS",
            "ZWZyZXNoVGltZRgCIAEoAxIyCg1EZWFsQXdhcmRJbmZvGAMgAygLMhsuR2Ft",
            "ZS5Qcm90b2NhbC5DU0dvb2RTdHJ1Y3QSMgoNRGVhbE5lZWRHb29kcxgEIAMo",
            "CzIbLkdhbWUuUHJvdG9jYWwuQ1NHb29kU3RydWN0EikKCERlYWxUeXBlGAUg",
            "ASgOMhcuR2FtZS5Qcm90b2NhbC5EZWFsVHlwZRIOCgZSb2xlSUQYBiABKAUS",
            "DgoGRGVzY0lEGAcgASgFIkwKClNDRGVhbEluZm8SLQoIRGVhbEluZm8YASAD",
            "KAsyGy5HYW1lLlByb3RvY2FsLlNDQ3JlYXRlRGVhbBIPCgdEZWFsTnVtGAIg",
            "AygFIh8KDUNTU3VibWludERlYWwSDgoGRGVhbElkGAEgASgFIkEKDVNDU3Vi",
            "bWludERlYWwSMAoLTmV3RGVhbEluZm8YASABKAsyGy5HYW1lLlByb3RvY2Fs",
            "LlNDQ3JlYXRlRGVhbCIfCg1DU1JlZnJlc2hEZWFsEg4KBkRlYWxJZBgBIAEo",
            "BSKXAQoNU0NSZWZyZXNoRGVhbBIyCg1EZWFsTmVlZEdvb2RzGAEgAygLMhsu",
            "R2FtZS5Qcm90b2NhbC5DU0dvb2RTdHJ1Y3QSMgoNRGVhbEF3YXJkSW5mbxgC",
            "IAMoCzIbLkdhbWUuUHJvdG9jYWwuQ1NHb29kU3RydWN0Eg4KBlJvbGVJRBgD",
            "IAEoBRIOCgZEZXNjSUQYBCABKAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Game.Protocal.WarehouseReflection.Descriptor, global::Game.Protocal.EnumTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Protocal.CSAdvSkipDeal), global::Game.Protocal.CSAdvSkipDeal.Parser, new[]{ "DealId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Protocal.SCCreateDeal), global::Game.Protocal.SCCreateDeal.Parser, new[]{ "DealId", "DealRefreshTime", "DealAwardInfo", "DealNeedGoods", "DealType", "RoleID", "DescID" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Protocal.SCDealInfo), global::Game.Protocal.SCDealInfo.Parser, new[]{ "DealInfo", "DealNum" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Protocal.CSSubmintDeal), global::Game.Protocal.CSSubmintDeal.Parser, new[]{ "DealId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Protocal.SCSubmintDeal), global::Game.Protocal.SCSubmintDeal.Parser, new[]{ "NewDealInfo" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Protocal.CSRefreshDeal), global::Game.Protocal.CSRefreshDeal.Parser, new[]{ "DealId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Protocal.SCRefreshDeal), global::Game.Protocal.SCRefreshDeal.Parser, new[]{ "DealNeedGoods", "DealAwardInfo", "RoleID", "DescID" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 订单广告跳过
  /// </summary>
  public sealed partial class CSAdvSkipDeal : pb::IMessage<CSAdvSkipDeal> {
    private static readonly pb::MessageParser<CSAdvSkipDeal> _parser = new pb::MessageParser<CSAdvSkipDeal>(() => new CSAdvSkipDeal());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CSAdvSkipDeal> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Protocal.DealReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSAdvSkipDeal() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSAdvSkipDeal(CSAdvSkipDeal other) : this() {
      dealId_ = other.dealId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSAdvSkipDeal Clone() {
      return new CSAdvSkipDeal(this);
    }

    /// <summary>Field number for the "DealId" field.</summary>
    public const int DealIdFieldNumber = 1;
    private int dealId_;
    /// <summary>
    /// 订单ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DealId {
      get { return dealId_; }
      set {
        dealId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CSAdvSkipDeal);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CSAdvSkipDeal other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DealId != other.DealId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DealId != 0) hash ^= DealId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DealId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(DealId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DealId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DealId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CSAdvSkipDeal other) {
      if (other == null) {
        return;
      }
      if (other.DealId != 0) {
        DealId = other.DealId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DealId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 生成订单信息
  /// </summary>
  public sealed partial class SCCreateDeal : pb::IMessage<SCCreateDeal> {
    private static readonly pb::MessageParser<SCCreateDeal> _parser = new pb::MessageParser<SCCreateDeal>(() => new SCCreateDeal());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SCCreateDeal> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Protocal.DealReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCCreateDeal() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCCreateDeal(SCCreateDeal other) : this() {
      dealId_ = other.dealId_;
      dealRefreshTime_ = other.dealRefreshTime_;
      dealAwardInfo_ = other.dealAwardInfo_.Clone();
      dealNeedGoods_ = other.dealNeedGoods_.Clone();
      dealType_ = other.dealType_;
      roleID_ = other.roleID_;
      descID_ = other.descID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCCreateDeal Clone() {
      return new SCCreateDeal(this);
    }

    /// <summary>Field number for the "DealId" field.</summary>
    public const int DealIdFieldNumber = 1;
    private int dealId_;
    /// <summary>
    /// 订单ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DealId {
      get { return dealId_; }
      set {
        dealId_ = value;
      }
    }

    /// <summary>Field number for the "DealRefreshTime" field.</summary>
    public const int DealRefreshTimeFieldNumber = 2;
    private long dealRefreshTime_;
    /// <summary>
    /// 订单刷新时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long DealRefreshTime {
      get { return dealRefreshTime_; }
      set {
        dealRefreshTime_ = value;
      }
    }

    /// <summary>Field number for the "DealAwardInfo" field.</summary>
    public const int DealAwardInfoFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Game.Protocal.CSGoodStruct> _repeated_dealAwardInfo_codec
        = pb::FieldCodec.ForMessage(26, global::Game.Protocal.CSGoodStruct.Parser);
    private readonly pbc::RepeatedField<global::Game.Protocal.CSGoodStruct> dealAwardInfo_ = new pbc::RepeatedField<global::Game.Protocal.CSGoodStruct>();
    /// <summary>
    /// 订单奖励信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Game.Protocal.CSGoodStruct> DealAwardInfo {
      get { return dealAwardInfo_; }
    }

    /// <summary>Field number for the "DealNeedGoods" field.</summary>
    public const int DealNeedGoodsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Game.Protocal.CSGoodStruct> _repeated_dealNeedGoods_codec
        = pb::FieldCodec.ForMessage(34, global::Game.Protocal.CSGoodStruct.Parser);
    private readonly pbc::RepeatedField<global::Game.Protocal.CSGoodStruct> dealNeedGoods_ = new pbc::RepeatedField<global::Game.Protocal.CSGoodStruct>();
    /// <summary>
    /// 订单需求道具
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Game.Protocal.CSGoodStruct> DealNeedGoods {
      get { return dealNeedGoods_; }
    }

    /// <summary>Field number for the "DealType" field.</summary>
    public const int DealTypeFieldNumber = 5;
    private global::Game.Protocal.DealType dealType_ = 0;
    /// <summary>
    /// 订单类型 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Game.Protocal.DealType DealType {
      get { return dealType_; }
      set {
        dealType_ = value;
      }
    }

    /// <summary>Field number for the "RoleID" field.</summary>
    public const int RoleIDFieldNumber = 6;
    private int roleID_;
    /// <summary>
    /// 角色ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RoleID {
      get { return roleID_; }
      set {
        roleID_ = value;
      }
    }

    /// <summary>Field number for the "DescID" field.</summary>
    public const int DescIDFieldNumber = 7;
    private int descID_;
    /// <summary>
    /// 对话ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DescID {
      get { return descID_; }
      set {
        descID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SCCreateDeal);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SCCreateDeal other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DealId != other.DealId) return false;
      if (DealRefreshTime != other.DealRefreshTime) return false;
      if(!dealAwardInfo_.Equals(other.dealAwardInfo_)) return false;
      if(!dealNeedGoods_.Equals(other.dealNeedGoods_)) return false;
      if (DealType != other.DealType) return false;
      if (RoleID != other.RoleID) return false;
      if (DescID != other.DescID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DealId != 0) hash ^= DealId.GetHashCode();
      if (DealRefreshTime != 0L) hash ^= DealRefreshTime.GetHashCode();
      hash ^= dealAwardInfo_.GetHashCode();
      hash ^= dealNeedGoods_.GetHashCode();
      if (DealType != 0) hash ^= DealType.GetHashCode();
      if (RoleID != 0) hash ^= RoleID.GetHashCode();
      if (DescID != 0) hash ^= DescID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DealId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(DealId);
      }
      if (DealRefreshTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(DealRefreshTime);
      }
      dealAwardInfo_.WriteTo(output, _repeated_dealAwardInfo_codec);
      dealNeedGoods_.WriteTo(output, _repeated_dealNeedGoods_codec);
      if (DealType != 0) {
        output.WriteRawTag(40);
        output.WriteEnum((int) DealType);
      }
      if (RoleID != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(RoleID);
      }
      if (DescID != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(DescID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DealId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DealId);
      }
      if (DealRefreshTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DealRefreshTime);
      }
      size += dealAwardInfo_.CalculateSize(_repeated_dealAwardInfo_codec);
      size += dealNeedGoods_.CalculateSize(_repeated_dealNeedGoods_codec);
      if (DealType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DealType);
      }
      if (RoleID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoleID);
      }
      if (DescID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DescID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SCCreateDeal other) {
      if (other == null) {
        return;
      }
      if (other.DealId != 0) {
        DealId = other.DealId;
      }
      if (other.DealRefreshTime != 0L) {
        DealRefreshTime = other.DealRefreshTime;
      }
      dealAwardInfo_.Add(other.dealAwardInfo_);
      dealNeedGoods_.Add(other.dealNeedGoods_);
      if (other.DealType != 0) {
        DealType = other.DealType;
      }
      if (other.RoleID != 0) {
        RoleID = other.RoleID;
      }
      if (other.DescID != 0) {
        DescID = other.DescID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DealId = input.ReadInt32();
            break;
          }
          case 16: {
            DealRefreshTime = input.ReadInt64();
            break;
          }
          case 26: {
            dealAwardInfo_.AddEntriesFrom(input, _repeated_dealAwardInfo_codec);
            break;
          }
          case 34: {
            dealNeedGoods_.AddEntriesFrom(input, _repeated_dealNeedGoods_codec);
            break;
          }
          case 40: {
            DealType = (global::Game.Protocal.DealType) input.ReadEnum();
            break;
          }
          case 48: {
            RoleID = input.ReadInt32();
            break;
          }
          case 56: {
            DescID = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 订单信息
  /// </summary>
  public sealed partial class SCDealInfo : pb::IMessage<SCDealInfo> {
    private static readonly pb::MessageParser<SCDealInfo> _parser = new pb::MessageParser<SCDealInfo>(() => new SCDealInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SCDealInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Protocal.DealReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCDealInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCDealInfo(SCDealInfo other) : this() {
      dealInfo_ = other.dealInfo_.Clone();
      dealNum_ = other.dealNum_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCDealInfo Clone() {
      return new SCDealInfo(this);
    }

    /// <summary>Field number for the "DealInfo" field.</summary>
    public const int DealInfoFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Game.Protocal.SCCreateDeal> _repeated_dealInfo_codec
        = pb::FieldCodec.ForMessage(10, global::Game.Protocal.SCCreateDeal.Parser);
    private readonly pbc::RepeatedField<global::Game.Protocal.SCCreateDeal> dealInfo_ = new pbc::RepeatedField<global::Game.Protocal.SCCreateDeal>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Game.Protocal.SCCreateDeal> DealInfo {
      get { return dealInfo_; }
    }

    /// <summary>Field number for the "DealNum" field.</summary>
    public const int DealNumFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_dealNum_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> dealNum_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// 订单完成数量详情
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> DealNum {
      get { return dealNum_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SCDealInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SCDealInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!dealInfo_.Equals(other.dealInfo_)) return false;
      if(!dealNum_.Equals(other.dealNum_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= dealInfo_.GetHashCode();
      hash ^= dealNum_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      dealInfo_.WriteTo(output, _repeated_dealInfo_codec);
      dealNum_.WriteTo(output, _repeated_dealNum_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += dealInfo_.CalculateSize(_repeated_dealInfo_codec);
      size += dealNum_.CalculateSize(_repeated_dealNum_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SCDealInfo other) {
      if (other == null) {
        return;
      }
      dealInfo_.Add(other.dealInfo_);
      dealNum_.Add(other.dealNum_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            dealInfo_.AddEntriesFrom(input, _repeated_dealInfo_codec);
            break;
          }
          case 18:
          case 16: {
            dealNum_.AddEntriesFrom(input, _repeated_dealNum_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 提交订单
  /// </summary>
  public sealed partial class CSSubmintDeal : pb::IMessage<CSSubmintDeal> {
    private static readonly pb::MessageParser<CSSubmintDeal> _parser = new pb::MessageParser<CSSubmintDeal>(() => new CSSubmintDeal());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CSSubmintDeal> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Protocal.DealReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSSubmintDeal() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSSubmintDeal(CSSubmintDeal other) : this() {
      dealId_ = other.dealId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSSubmintDeal Clone() {
      return new CSSubmintDeal(this);
    }

    /// <summary>Field number for the "DealId" field.</summary>
    public const int DealIdFieldNumber = 1;
    private int dealId_;
    /// <summary>
    /// 订单ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DealId {
      get { return dealId_; }
      set {
        dealId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CSSubmintDeal);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CSSubmintDeal other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DealId != other.DealId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DealId != 0) hash ^= DealId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DealId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(DealId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DealId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DealId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CSSubmintDeal other) {
      if (other == null) {
        return;
      }
      if (other.DealId != 0) {
        DealId = other.DealId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DealId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 提交订单返回
  /// </summary>
  public sealed partial class SCSubmintDeal : pb::IMessage<SCSubmintDeal> {
    private static readonly pb::MessageParser<SCSubmintDeal> _parser = new pb::MessageParser<SCSubmintDeal>(() => new SCSubmintDeal());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SCSubmintDeal> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Protocal.DealReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCSubmintDeal() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCSubmintDeal(SCSubmintDeal other) : this() {
      newDealInfo_ = other.newDealInfo_ != null ? other.newDealInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCSubmintDeal Clone() {
      return new SCSubmintDeal(this);
    }

    /// <summary>Field number for the "NewDealInfo" field.</summary>
    public const int NewDealInfoFieldNumber = 1;
    private global::Game.Protocal.SCCreateDeal newDealInfo_;
    /// <summary>
    /// 订单信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Game.Protocal.SCCreateDeal NewDealInfo {
      get { return newDealInfo_; }
      set {
        newDealInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SCSubmintDeal);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SCSubmintDeal other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(NewDealInfo, other.NewDealInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (newDealInfo_ != null) hash ^= NewDealInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (newDealInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(NewDealInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (newDealInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NewDealInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SCSubmintDeal other) {
      if (other == null) {
        return;
      }
      if (other.newDealInfo_ != null) {
        if (newDealInfo_ == null) {
          NewDealInfo = new global::Game.Protocal.SCCreateDeal();
        }
        NewDealInfo.MergeFrom(other.NewDealInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (newDealInfo_ == null) {
              NewDealInfo = new global::Game.Protocal.SCCreateDeal();
            }
            input.ReadMessage(NewDealInfo);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 刷新订单 
  /// </summary>
  public sealed partial class CSRefreshDeal : pb::IMessage<CSRefreshDeal> {
    private static readonly pb::MessageParser<CSRefreshDeal> _parser = new pb::MessageParser<CSRefreshDeal>(() => new CSRefreshDeal());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CSRefreshDeal> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Protocal.DealReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSRefreshDeal() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSRefreshDeal(CSRefreshDeal other) : this() {
      dealId_ = other.dealId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSRefreshDeal Clone() {
      return new CSRefreshDeal(this);
    }

    /// <summary>Field number for the "DealId" field.</summary>
    public const int DealIdFieldNumber = 1;
    private int dealId_;
    /// <summary>
    /// 订单ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DealId {
      get { return dealId_; }
      set {
        dealId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CSRefreshDeal);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CSRefreshDeal other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DealId != other.DealId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DealId != 0) hash ^= DealId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DealId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(DealId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DealId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DealId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CSRefreshDeal other) {
      if (other == null) {
        return;
      }
      if (other.DealId != 0) {
        DealId = other.DealId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DealId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 刷新订单返回
  /// </summary>
  public sealed partial class SCRefreshDeal : pb::IMessage<SCRefreshDeal> {
    private static readonly pb::MessageParser<SCRefreshDeal> _parser = new pb::MessageParser<SCRefreshDeal>(() => new SCRefreshDeal());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SCRefreshDeal> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Protocal.DealReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCRefreshDeal() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCRefreshDeal(SCRefreshDeal other) : this() {
      dealNeedGoods_ = other.dealNeedGoods_.Clone();
      dealAwardInfo_ = other.dealAwardInfo_.Clone();
      roleID_ = other.roleID_;
      descID_ = other.descID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCRefreshDeal Clone() {
      return new SCRefreshDeal(this);
    }

    /// <summary>Field number for the "DealNeedGoods" field.</summary>
    public const int DealNeedGoodsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Game.Protocal.CSGoodStruct> _repeated_dealNeedGoods_codec
        = pb::FieldCodec.ForMessage(10, global::Game.Protocal.CSGoodStruct.Parser);
    private readonly pbc::RepeatedField<global::Game.Protocal.CSGoodStruct> dealNeedGoods_ = new pbc::RepeatedField<global::Game.Protocal.CSGoodStruct>();
    /// <summary>
    /// 需求道具信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Game.Protocal.CSGoodStruct> DealNeedGoods {
      get { return dealNeedGoods_; }
    }

    /// <summary>Field number for the "DealAwardInfo" field.</summary>
    public const int DealAwardInfoFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Game.Protocal.CSGoodStruct> _repeated_dealAwardInfo_codec
        = pb::FieldCodec.ForMessage(18, global::Game.Protocal.CSGoodStruct.Parser);
    private readonly pbc::RepeatedField<global::Game.Protocal.CSGoodStruct> dealAwardInfo_ = new pbc::RepeatedField<global::Game.Protocal.CSGoodStruct>();
    /// <summary>
    /// 订单奖励配置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Game.Protocal.CSGoodStruct> DealAwardInfo {
      get { return dealAwardInfo_; }
    }

    /// <summary>Field number for the "RoleID" field.</summary>
    public const int RoleIDFieldNumber = 3;
    private int roleID_;
    /// <summary>
    /// 角色ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RoleID {
      get { return roleID_; }
      set {
        roleID_ = value;
      }
    }

    /// <summary>Field number for the "DescID" field.</summary>
    public const int DescIDFieldNumber = 4;
    private int descID_;
    /// <summary>
    /// 对话ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DescID {
      get { return descID_; }
      set {
        descID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SCRefreshDeal);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SCRefreshDeal other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!dealNeedGoods_.Equals(other.dealNeedGoods_)) return false;
      if(!dealAwardInfo_.Equals(other.dealAwardInfo_)) return false;
      if (RoleID != other.RoleID) return false;
      if (DescID != other.DescID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= dealNeedGoods_.GetHashCode();
      hash ^= dealAwardInfo_.GetHashCode();
      if (RoleID != 0) hash ^= RoleID.GetHashCode();
      if (DescID != 0) hash ^= DescID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      dealNeedGoods_.WriteTo(output, _repeated_dealNeedGoods_codec);
      dealAwardInfo_.WriteTo(output, _repeated_dealAwardInfo_codec);
      if (RoleID != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(RoleID);
      }
      if (DescID != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(DescID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += dealNeedGoods_.CalculateSize(_repeated_dealNeedGoods_codec);
      size += dealAwardInfo_.CalculateSize(_repeated_dealAwardInfo_codec);
      if (RoleID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoleID);
      }
      if (DescID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DescID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SCRefreshDeal other) {
      if (other == null) {
        return;
      }
      dealNeedGoods_.Add(other.dealNeedGoods_);
      dealAwardInfo_.Add(other.dealAwardInfo_);
      if (other.RoleID != 0) {
        RoleID = other.RoleID;
      }
      if (other.DescID != 0) {
        DescID = other.DescID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            dealNeedGoods_.AddEntriesFrom(input, _repeated_dealNeedGoods_codec);
            break;
          }
          case 18: {
            dealAwardInfo_.AddEntriesFrom(input, _repeated_dealAwardInfo_codec);
            break;
          }
          case 24: {
            RoleID = input.ReadInt32();
            break;
          }
          case 32: {
            DescID = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
