// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EnumType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Game.Protocal {

  /// <summary>Holder for reflection information generated from EnumType.proto</summary>
  public static partial class EnumTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for EnumType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5FbnVtVHlwZS5wcm90bxINR2FtZS5Qcm90b2NhbCrAJwoJRXJyb3JDb2Rl",
            "EggKBE5vbmUQABILCgdTdWNjZXNzEAESDwoLT3BDb2RlX051bGwQAhITCg5T",
            "ZW5kX0RhdGFfTnVsbBDQDxIlCiBTZXJ2ZXJSZXBvcnRfU2VydmVyUmVxRGVj",
            "b2RlRmFpbBC4FxIQCgtNeXNxbF9FcnJvchCgHxIaChVSZXF1ZXN0RXJyb3Jf",
            "Tm9NZXRob2QQoR8SFAoPU2VydmVyRXhjZXB0aW9uEKIfEhsKFlJlcXVlc3Rf",
            "RXNzZW50aWFsX051bGwQox8SFgoRQWNjb3VudF9BYm5vcm1pdHkQkk4SFgoR",
            "QWNjb3VudF9BZGRfRXJyb3IQk04SFwoSQWNjb3VudF9SZXBldGl0aW9uEJVO",
            "EhYKEUFjY291bnRfU29sZV9OdWxsEJZOEhgKE0FjY291bnRfSW5leGlzdGVu",
            "Y2UQl04SGgoVQWNjb3VudF9TZXROYW1lX0Vycm9yEJhOEhsKFkFjY291bnRf",
            "U2V0SW1hZ2VfRXJyb3IQmU4SHAoXQWNjb3VudF9aaWxsaW9uYWlyZV9NYXAQ",
            "nU4SIAobQWNjb3VudF9aaWxsaW9uYWlyZV9BY3F1aXJlEJ5OEh4KGUFjY291",
            "bnRfVXBHcmFkZV9Ob25lQXdhcmQQn04SGAoTQWNjb3VudF9Vc2VyX0NvbmZp",
            "ZxCgThIWChFBY2NvdW50X1VzZXJfSW5mbxChThIfChpBY2NvdW50X1NldE5h",
            "bWVfUmVwZXRpdGlvbhCiThIZChRBY2NvdW50X0ltYWdlX0NvbmZpZxCjThIV",
            "ChBBY2NvdW50X05vX0ltYWdlEKROEhcKEkFjY291bnRfSW1hZ2VfSW5mbxCl",
            "ThIZChRBY2NvdW50X0xvZ291dF9FcnJvchCmThIVCg9GcmllbmRfQWRkX0Zh",
            "aWwQpJwBEhYKEEZyaWVuZF9BZGRfQWdhaW4QpZwBEhUKD0ZyaWVuZF9EZWxf",
            "RmFpbBCmnAESGAoSRnJpZW5kX1NlYXJjaF9GYWlsEMeaDBIQCgpGcmllbmRf",
            "TWF4EMiaDBIXChFVc2VyX05vdF9FeGlzdGVudBDKmgwSFwoRRnJpZW5kX1Jl",
            "ZnVzZV9BZGQQzZoMEhUKD01hcF9JbmV4aXN0ZW5jZRCkmwwSGAoSTWFwX1Jl",
            "cGV0aXRpb25fQnV5EKabDBIkCh5NYXBfUGh5c2ljYWxQb3dlcl9JbnN1ZmZp",
            "Y2llbnQQp5sMEhgKEk1hcF9QdXJjaGFzZV9MaW1pdBCpmwwSGgoUTWFwX1Jv",
            "bGVfSW5leGlzdGVuY2UQq5sMEhcKEU1hcF9Sb2xlX2RlZmVhdGVkEKybDBIY",
            "ChJNYXBfQXdhcmRfRGVmZWF0ZWQQrZsMEhYKEE1hcF9SZWNvcmRfQXdhcmQQ",
            "rpsMEhYKEE1hcF9CdXlfRGVmZWF0ZWQQsZsMEhkKE01hcF9DaG9pY2VfRGVm",
            "ZWF0ZWQQspsMEhUKD01hcF9QbGFudF9MaW1pdBCzmwwSFgoQTWFwX0NvdW50",
            "X0ZpbmlzaBC2mwwSFgoQTWFwX0NvdW50X0RlZHVjdBC3mwwSEwoNTWFwX0Rp",
            "Y2VfVHlwZRC4mwwSFwoRTWFwX0RpY2VfRGVmZWF0ZWQQuZsMEhQKDk1hcF9M",
            "dWNreV9UeXBlELqbDBIUCg5NYXBfTHVja3lfUHJvcBC7mwwSFAoOTWFwX0x1",
            "Y2t5X1NlZWQQvJsMEhUKD01hcF9MdWNreV9Db3VudBC9mwwSGAoSTWFwX0x1",
            "Y2t5X0RlZmVhdGVkEL6bDBIZChNNYW5vcl9EcmFnX0RlZmVhdGVkEPixDBIe",
            "ChhNYW5vcl9FcmFkaWNhdGVfRGVmZWF0ZWQQ+rEMEhsKFU1hbm9yX0NoYW5n",
            "ZV9Qb3NpdGlvbhD8sQwSEwoNTWFub3JfSGFydmVzdBD9sQwSFgoQTWFub3Jf",
            "UGxhbnRfTnVsbBD+sQwSFQoPTWFub3JfTm9uZV9JbmZvEP+xDBIaChRNYW5v",
            "cl9Dcm9wX0FkdWx0bmVzcxCAsgwSGgoUTWFub3JfVXNlX0ZlcnRpbGl6ZXIQ",
            "grIMEhcKEU1hbm9yX1BhcmNlbF9JbmZvEIOyDBIcChZNYW5vcl9SZWN5Y2xl",
            "X0RlY29yYXRlEIayDBIUCg5NYW5vcl9Ob19QbGFudBCHsgwSGwoVTWFub3Jf",
            "UmVtb3ZlX0RlZmVhdGVkEIiyDBIcChZNYW5vcl9IYXJ2ZXN0X0RlZmVhdGVk",
            "EImyDBIYChJNYW5vcl9EZWR1Y3RfR29vZHMQirIMEhkKE01hbm9yX1N0ZWFs",
            "X09uZXNlbGYQjLIMEhQKDk1hbm9yX1N0ZWFsX05vEI2yDBIXChFNYW5vcl9V",
            "bmxvY2tfSW5mbxCPsgwSGgoUTWFub3JfSGFydmVzdF9GaW5pc2gQkbIMEhwK",
            "Fk1hbm9yX0hhcnZlc3RfTGF0ZW5lc3MQkrIMEhgKEk1hbm9yX05ld19EZWZl",
            "YXRlZBCTsgwSFgoQTWFub3JfQXJlYV9TdGF0ZRCUsgwSGAoSTWFub3JfQWNx",
            "dWlyZV9BcmVhEJWyDBIaChRNYW5vcl9Sb2Fkd29ya19TdGFnZRCWsgwSGgoU",
            "TWFub3JfUm9hZHdvcmtfU3BlZWQQl7IMEhkKE01hbm9yX0tleV9Ob3Rlbm91",
            "Z2gQmrIMEhkKE01hbm9yX1JlY3ljbGVfRXJyb3IQm7IMEhoKFE1hbm9yX0Jv",
            "eFVubG9ja19UaW1lEJyyDBIWChBNYW5vcl9Cb3hfVW5sb2NrEJ2yDBIXChFN",
            "YW5vcl9Cb3hfUmVjeWNsZRCesgwSEgoMTWFub3JfTm9fQm94EJ+yDBITCg1N",
            "YW5vcl9Cb3hfR2V0EKCyDBIgChpNYW5vcl9Cb3hfVXBkYXRlVW5sb2NrVElt",
            "ZRChsgwSGgoUTWFub3JfRGlnbGV0dF9OdW1NYXgQorIMEh4KGE1hbm9yX0Rp",
            "Z2xldHRXYXJhZF9FcnJvchCjsgwSJAoeTWFub3JfRnJpZW5kTWFub3JEaWds",
            "ZXR0X0FnYWluEKSyDBIgChpNYW5vcl9GcmllbmREaWdsZXR0X015c2VsZhCl",
            "sgwSGgoUTWFub3JfU3RlYWxMb2dfRXJyb3IQprIMEiAKGk1hbm9yX01hbm9y",
            "RHJhZ19Ob0RlY29yYXRlEKeyDBIXChFNYW5vcl9GcmVlX051bWJlchCosgwS",
            "GQoTTWFub3JfRnJlZV9EZWZlYXRlZBCpsgwSHAoWTWFub3JfVGhpc0Nyb3Bf",
            "RG9uVEJ1eRCqsgwSIAoaTWFub3JfRGVjb3JhdGVSb3RhdGVfRXJyb3IQq7IM",
            "EhYKEE1hbm9yX1dhdGVyX051bGwQrLIMEhUKD01hbm9yX1VzZV9XYXRlchCt",
            "sgwSEwoNR29vZF9JZF9FcnJvchDJwQwSEgoMR29vZF9Db25zdW1lEMrBDBIX",
            "ChFHb29kX1VwZGF0ZV9FcnJvchDMwQwSFQoPR29vZF9Mb2NrX0Vycm9yEM7B",
            "DBIVCg9Hb29kX1NlbGxfRXJyb3IQz8EMEhoKFEdvb2RfR29sZGpld2VsX0Vy",
            "cm9yENHBDBIdChdHb29kX0pld2VsX0luc3VmZmljaWVudBDSwQwSGAoSU3Rv",
            "cmVfQ29uZmlnX0Vycm9yENPBDBIWChBKZXdlbF9UcmFkZV9Hb2xkENTBDBIc",
            "ChZHb29kX1JlZHVjZWpld2VsX0Vycm9yENXBDBIhChtHb29kX1dhcmVob3Vz",
            "ZV9JbnN1ZmZpY2llbnQQ1sEMEhoKFEdvb2RfR29vZHNsb2NrX0Vycm9yENfB",
            "DBIXChFHb29kX0J1eWdvb2RzX01heBDYwQwSGgoUR29vZF9EZWR1Y3RfRGVm",
            "ZWF0ZWQQ2sEMEhIKDEdvb2RfTm9fSW5mbxDbwQwSGwoVR29kZF9TdG9yYWdl",
            "X0RlZmVhdGVkEN3BDBIXChFHb29kX0NvbmZpZ19FcnJvchDewQwSGQoTR29v",
            "ZF9CdXlUaW1lX0V4Y2VlZBDfwQwSHQoXTWFpbF9HZXRhY2Nlc3NvcnlfRXJy",
            "b3IQsckMEiAKGk1haWxfR2V0YWNjZXNzb3J5X0RlZmVhdGVkELLJDBIgChpN",
            "YWlsX0NoYW5nZU1haWxTdGF0ZV9FcnJvchC0yQwSGgoUU2VjaXRvbl9Vbmxv",
            "Y2tfRXJyb3IQmtEMEiYKIEV4dHJhU3RvcnlfWml4aW5nYmlfSW5zdWZmaWNp",
            "ZW50EJvRDBIfChlFeHRyYVN0b3J5X1ppeGluZ2JpX0Vycm9yEJzRDBIZChNC",
            "dXlFeHRyYVN0b3J5X0Vycm9yEJ3RDBIWChBTZWN0aW9uX0J1eV9JbmZvEJ/R",
            "DBIYChJTZWN0aW9uX0V4dHJhX0luZm8QoNEMEh0KF1NlY3Rpb25fQ2xlYXJh",
            "bmNlX0Vycm9yEKHRDBIcChZTZWN0aW9uX1JlcGV0aXRpb25fQnV5EKLRDBIW",
            "ChBTZWN0aW9uX0J1eV9OZXh0EKPRDBIWChBTZWN0aW9uX05ld19PcGVuEKTR",
            "DBIfChlXYXJlaG91c2VfRGV0YWlsX0RlZmVhdGVkEIHZDBIdChdXYXJlaG91",
            "c2VfQm94SW5mb19FcnJvchCE2QwSIAoaV2FyZUhvdXNlX0JveEtleV9Ob3RF",
            "bm91Z2gQhdkMEh8KGVdhcmVIb3VzZV9Cb3hVbmxvY2tfRXJyb3IQhtkMEicK",
            "IVdhcmVIb3VzZV9Cb3hVbmxvY2tUaW1lX05vdEVub3VnaBCH2QwSKQojV2Fy",
            "ZUhvdXNlX1VwZGF0ZUJveFVubG9ja0luZm9fRXJyb3IQidkMEh8KGVdhcmVI",
            "b3VzZV9EZWxCb3hOdW1fRXJyb3IQitkMEiAKGldhcmVIb3VzZV9Cb3hTcGVl",
            "ZF9GYWlsdXJlEIvZDBIhChtXYXJlSG91c2VfR2l0ZkJveEluZm9fRXJyb3IQ",
            "jtkMEh4KGFdhcmVIb3VzZV9Vc2VHb29kc19FcnJvchCS2QwSFAoOQ29uZmln",
            "X05vX0luZm8Q6eAMEh8KGUFkdmVydGlzaW5nX1NwZWVkX0Fub21hbHkQ6uAM",
            "EhIKDFNpZ25fSW5fRmFpbBDc5AwSGgoUU2lnbl9BY2N1bXVsYXRlX0ZhaWwQ",
            "3eQMEhwKFlNpZ25fQWNjdW11bGF0ZV9Fbm91Z2gQ3uQMEhsKFVNpZ25fQWNj",
            "dW11bGF0ZV9Bd2FyZBDf5AwSFQoPU2lnbl9Bd2FyZF9GYWlsEODkDBIeChhT",
            "aWduX0V2ZXJ5ZGF5X1JlcGV0aXRpb24Q4eQMEhcKEVNlbmRfTWVzc2FnZV9O",
            "dWxsEOGnEhIdChdJbXB1bHNlX0dldENvbmZpZ19FcnJvchCBtRgSHQoXSW1w",
            "dWxzZV9TZW5kX0dpZnRfRXJyb3IQhLUYEiIKHEltcHVsc2VfU2VjdGlvbl9P",
            "cHRpb25fRXJyb3IQhbUYEiIKHEltcHVsc2VfQWRkX1NlY3Rpb25fT3B0aW9u",
            "ZWQQhrUYEiUKH0ltcHVsc2VfR2V0TG9naW5GYXZvcmFibGVfRXJyb3IQh7UY",
            "EiUKH0ltcHVsc2VfU2VjdGlvbl9GYXZvcmFibGVfQWdhaW4QiLUYEhcKEVNl",
            "Y3Rpb25fUm9vbV9OdWxsEKHCHhIcChZTZWN0aW9uX1Jvb21fQWJub3JtaXR5",
            "EKLCHhIYChJTZWN0aW9uX1Jvb21fTGltaXQQo8IeEhkKE1NlY3Rpb25fQWJz",
            "ZW50X1Jvb20QpMIeEhgKElNlY3Rpb25fTm9fUmVjZWl2ZRClwh4SGwoVU2Vj",
            "dGlvbl9HdWVzc2luZ19OdWxsEKbCHhIbChVTZWN0aW9uX01vdmVfUG9zaXRp",
            "b24Qp8IeEhsKFVNlY3Rpb25fQmV0VGltZV9FcnJvchCowh4SHAoWU2VjdGlv",
            "bl9Jc0VuZE9yTm90T3BlbhCpwh4SEAoKUm9sZV9Jc093bhDBzyQSGwoVUm9s",
            "ZV9Db25maWdfRG9udEV4aXN0EMLPJBIbChVSb2xlX1N3aXRjaFJvbGVfRXJy",
            "b3IQxc8kEhsKFVJvbGVfSGFsbFVwZGF0ZV9FcnJvchDGzyQSGAoSUm9sZV9M",
            "aXN0X0RlZmVhdGVkEMfPJBIXChFSb2xlX0FkZF9EZWZlYXRlZBDIzyQSFwoR",
            "Um9sZV9Db3N0dW1lX0luZm8Qyc8kEhoKFFJvbGVfQ29zdHVtZV9SZW5ld2Fs",
            "EMrPJBIcChZHdWlkYW5jZV9TYXZlX0RlZmVhdGVkEJHWJxIXChFHdWlkYW5j",
            "ZV9BYm5vcm1hbBCS1icSFQoPR3VpZGFuY2VfRmluaXNoEJPWJxIWChBHdWlk",
            "YW5jZV9Ob19JbmZvEJTWJxIZChNUYXNrX0dldEF3YXJkX0Vycm9yEOHcKhIi",
            "ChxUYXNrX0dldFRhc2tFeHBlcmllbmNlX0Vycm9yEOLcKhIYChJGdW5jdGlv",
            "bl9Jc05vdE9wZW4QgeowEh8KGURlYWxfQ3VycmVudE5vdERlYWxTdWJtaXQQ",
            "ofc2Eh4KGERlYWxfQ3VycmVudFN1Yk1pdF9FcnJvchCi9zYSFwoRRGVhbF9T",
            "dWJtaXRfRXJyb3IQo/c2EhgKEkRlYWxfUmVmcmVzaF9FcnJvchCk9zYSFQoP",
            "RGVhbF9EYXRhSXNOdWxsEKX3NhIcChZEZWFsX1NraXBEZWFsQWR2X0Vycm9y",
            "EKb3NhIXChFEZWFsX0dldEV4cF9FcnJvchCn9zYSEwoNRGVhbF9PbkNEVGlt",
            "ZRCo9zYqwREKCk9wQ29kZVR5cGUSEgoOT3BDb2RlVHlwZU5vbmUQABIPCgtM",
            "b2FkQmFsYW5jZRABEg8KC0FjY291bnRJbmZvEAISDgoKQmFzaWNzSW5mbxAD",
            "EhQKEEdldENvbm5lY3RTZXJ2ZXIQBBIRCg1HZXRGcmllbmRMaXN0EAUSEAoM",
            "R2V0QXBwbHlMaXN0EAYSFAoQR2V0UmVmZXJyYWxzTGlzdBAHEgwKCEFwcGx5",
            "QWRkEAgSDQoJQWNjZXB0QWRkEAkSDgoKUmVwdWxzZUFkZBAKEg0KCURlbEZy",
            "aWVuZBALEg4KClNlYXJjaFVzZXIQDBITCg9FbnRlclJpY2hNYW5NYXAQDRIP",
            "CgtSaWNoTWFuRGljZRAOEhEKDVJpY2hNYW5GaW5pc2gQDxINCglSaWNoTHVj",
            "a3kQEBINCglDcm9wU3BlZWQQERILCgdCdXlQcm9wEBISCAoERHJhZxATEhAK",
            "DEdldE1hbm9ySW5mbxAUEg4KCkZlcnRpbGl6ZXIQFRINCglFcmFkaWNhdGUQ",
            "FhIJCgVQbGFudBAXEgsKB0hhcnZlc3QQGBIJCgVTdGVhbBAZEhIKDkNoYW5n",
            "ZUxvY2F0aW9uEBoSDAoIR29vZFNlbGwQGxIMCghHb29kTG9jaxAcEhMKD1F1",
            "ZXJ5T3RoZXJNYW5vchAdEg4KClVubG9ja0FyZWEQHhIPCgtHZXRSb2xlTGlz",
            "dBAfEg4KCkNob2ljZVJvbGUQIBILCgdCdXlSb2xlECESFwoTUHJvbW90aW9u",
            "c0dvb2RzSW5mbxAiEg0KCUdvbGRKZXdlbBAjEg4KCkJ1eVNlY3Rpb24QJBIT",
            "Cg9DbGVhcmFuY2VTdGNpb24QJRIVChFPcm5hbWVudGFsUmVjeWNsZRAmEhEK",
            "DVRyZWFzdXJlQ2hlc3QQJxIWChJUcmVhc3VyZUNoZXN0QXdhcmQQKBIMCghN",
            "YW5vckJveBApEhEKDUNsaWNrTWFub3JCb3gQKhIRCg1CdXlFeHRyYVN0b3J5",
            "ECsSCwoHR2V0TWFpbBAsEhAKDEdldEFjY2Vzc29yeRAtEhQKEEdldEFjY2Vz",
            "c29yeUluZm8QLhIKCgZTaWduSW4QLxIPCgtGcmllbmRNYW5vchAxEg8KC1Vz",
            "ZXJVcEdyYWdlEDISDgoKQm94U3BlZWRVcBA0EhMKD1dvcmtTaGVkU3BlZWRV",
            "cBA1EhoKFldhcmVIb3VzZUJveFVubG9ja0luZm8QNhIVChFXYXJlSG91c2VC",
            "b3hTcGVlZBA3EhUKEVVzZVdhcmVob3VzZUdvb2RzEDgSEAoMR2V0TWFub3JM",
            "b2dzEDkSEAoMUHVyY2hhc2VSb2xlEDoSEgoOU3dpdGNob3ZlclJvbGUQOxIV",
            "ChFTd2l0Y2hvdmVyQ29zdHVtZRA8EhEKDU9uZXNlbGZNYXJtb3QQPRIQCgxG",
            "cmllbmRNYXJtb3QQPhIRCg1BZHZFeHRyYVN0b3J5ED8SDQoJV29ybGRDaGF0",
            "EEASDwoLUHJpdmF0ZUNoYXQQQRIQCgxFbnRyYW5jZVJvb20QQhIMCghHdWVz",
            "c2luZxBDEg8KC0NoYW5uZWxDaGF0EEQSDAoIUm9vbUxpc3QQRRIVChFMb2dp",
            "bkdldEZhdm9yYWJsZRBGEg8KC1NlbmROUENHaWZ0EEcSFwoTU2VjdGlvbkFk",
            "ZEZhdm9yYWJsZRBIEhQKEEdldEZhdm9yYWJsZUluZm8QShIQCgxNb3ZlTG9j",
            "YXRpb24QSxIRCg1EZXBhcnR1cmVSb29tEEwSCgoGTW90aW9uEE4SFgoSR2V0",
            "TWFybW90QXdhcmRJbmZvEE8SEwoPQ2hhbmdlTWFpbFN0YXRlEFASEwoPU2hv",
            "cHBpbmdUcm9sbGV5EFESDQoJSGVhcnRCZWF0EFISFAoQQWNjdW11bGF0ZVNp",
            "Z25JbhBTEhAKDFNhdmVHdWlkYW5jZRBUEhEKDU1hbm9yR3VpZGFuY2UQVxIW",
            "ChJTdGVhbE1hbm9yR3VpZGFuY2UQWBIPCgtHZXRUYXNrSW5mbxBbEhAKDEdl",
            "dFRhc2tBd2FyZBBcEhEKDUxvZ291dEFjY291bnQQXRIRCg1DZGtDb252ZXJz",
            "aW9uEF4SDwoLR2V0RGVhbEluZm8QXxIOCgpTdWJtaXREZWFsEGASDwoLUmVm",
            "cmVzaERlYWwQYRIPCgtBZHZTa2lwRGVhbBBiEhMKD0VudHJhbmNlU2VjdGlv",
            "bhBjEg4KCkNyb3BNYXR1cmUQZBIXChNNYW5vckRlY29yYXRlUm90YXRlEGUS",
            "DgoKRnJpZW5kTGlrZRBmEhEKDUZyaWVuZENvc3R1bWUQZxIQCgxPbmNlV2F0",
            "ZXJpbmcQaBIOCgpEZWNvcmF0ZVVwEGkSDwoJVGVzdF9EYXRhENCGAxIYChJS",
            "ZXBldGl0aW9uUmVnaXN0ZXIQ0YYDEhQKDkFwcGx5QWRkRnJpZW5kENKGAxIV",
            "Cg9BY2NlcHRBZGRGcmllbmQQ04YDEhYKEFJlcHVsc2VBZGRGcmllbmQQ1IYD",
            "EhIKDERlbGV0ZUZyaWVuZBDVhgMSDgoITWFpbFB1c2gQ1oYDEhEKC01hbm9y",
            "RnJpZW5kENeGAxISCgxQdXNoTm90ZU1lc3MQ2YYDEhMKDVB1c2hWb2ljZU1l",
            "c3MQ2oYDEhMKDVB1c2hXb3JsZENoYXQQ24YDEhUKD1B1c2hQcml2YXRlQ2hh",
            "dBDchgMSFQoPUHVzaENoYW5uZWxDaGF0EN2GAxIaChRQdXNoRW50cmFuY2VS",
            "b29tSW5mbxDehgMSFgoQUHVzaE1vdmVMb2NhdGlvbhDfhgMSEgoMUHVzaEd1",
            "ZXNzaW5nEOCGAxIQCgpQdXNoTW90aW9uEOGGAxIXChFQdXNoRGVwYXJ0dXJl",
            "Um9vbRDihgMSGAoSUHVzaEFjdGl2aXR5RmluaXNoEOOGAxIcChZQdXNoUmVw",
            "ZXRpdGlvblJlZ2lzdGVyEOSGAxIXChFQdXNoQ29lcmNlUmVuZXdhbBDg1AMq",
            "PgoMU2VydmVyU3RhdHVzEhQKEFNlcnZlclN0YXR1c05vbmUQABIKCgZOb3Jt",
            "YWwQARIMCghNYWludGFpbhACKkAKEFJlZ2lzdGVyUGxhdGZvcm0SGAoUUmVn",
            "aXN0ZXJQbGF0Zm9ybU5vbmUQABIGCgJRcRABEgoKBldlQ2hhdBACKjwKC21h",
            "bm9yTWF0dXJlEhMKD21hbm9yTWF0dXJlTm9uZRAAEgoKBm1hdHVyZRABEgwK",
            "CGltbWF0dXJlEAIqzgIKDldlYnNjb2VrdEVycm9yEhYKEldlYnNjb2VrdEVy",
            "cm9yTm9uZRAAEhAKC0NMT1NFTk9STUFMEOgHEhMKDkNMT1NFR09JTkdBV0FZ",
            "EOkHEhcKEkNMT1NFUFJPVE9DT0xFUlJPUhDqBxIVChBDTE9TRVVOU1VQUE9S",
            "VEVEEOsHEhIKDUNMT1NFTk9TVEFUVVMQ7QcSEgoNQ0xPU0VBQk5PUk1BTBDu",
            "BxIUCg9VbnN1cHBvcnRlZERhdGEQ7wcSFAoPUG9saWN5VmlvbGF0aW9uEPAH",
            "EhIKDUNMT1NFVE9PTEFSR0UQ8QcSFQoQTWlzc2luZ0V4dGVuc2lvbhDyBxIS",
            "Cg1JbnRlcm5hbEVycm9yEPMHEhMKDlNlcnZpY2VSZXN0YXJ0EPQHEhIKDVRy",
            "eUFnYWluTGF0ZXIQ9QcSEQoMVExTSGFuZHNoYWtlEPcHKmMKClNlcnZlclR5",
            "cGUSEgoOU2VydmVyVHlwZU5vbmUQABIOCgpMaW5rU2VydmVyEAESDwoLTG9n",
            "aWNTZXJ2ZXIQAhIOCgpDaGF0U2VydmVyEAMSEAoMU29pcmVlU2VydmVyEAQq",
            "XAoKTWFub3JTY2VuZRISCg5NYW5vclNjZW5lTm9uZRAAEggKBFRpbGUQARIM",
            "CghEb2dIb3VzZRACEgsKB0dpZnRCb3gQAxIMCghEZWNvcmF0ZRAEEgcKA05w",
            "YxAFKkEKD0NvbnN1bXB0aW9uVHlwZRIXChNDb25zdW1wdGlvblR5cGVOb25l",
            "EAASCAoER29sZBABEgsKB0RpYW1vbmQQAipKChNVbmxvY2tUcmVhc3VyZUNo",
            "ZXN0EhsKF1VubG9ja1RyZWFzdXJlQ2hlc3ROb25lEAASBwoDS2V5EAESDQoJ",
            "Q291bnREb3duEAIqOwoKUGVyaW9kR3JvdxIICgRTZWVkEAASDQoJR2VybWlu",
            "YXRlEAESCgoGR3Jvd1VwEAISCAoEUmlwZRADKmQKCUFyZWFTdGF0ZRIMCghO",
            "b1VubG9jaxAAEhAKDENvbnZlcnNhdGlvbhABEgcKA1BheRACEgwKCFJvYWRX",
            "b3JrEAMSDAoIV29ya1NoZWQQBBISCg5SZW1vdmVXb3JrU2hlZBAFKj8KC0lz",
            "UHJvbW90aW9uEhMKD0lzUHJvbW90aW9uTm9uZRAAEgwKCE9yaWdpbmFsEAES",
            "DQoJUHJvbW90aW9uEAIqPwoLR29vZHNCdXlXYXkSEwoPR29vZHNCdXlXYXlO",
            "b25lEAASDAoIRmlyc3RXYXkQARINCglTZWNvbmRXYXkQAipUChJXb3JrU2hl",
            "ZFNwZWVkVXBXYXkSGgoWV29ya1NoZWRTcGVlZFVwV2F5Tm9uZRAAEhIKDkFk",
            "dmVydGlzaW5nV2F5EAESDgoKRGlhbW9uZFdheRACKocBChVXYXJlaG91c2VT",
            "aGllbGRJRExpc3QSHQoZV2FyZWhvdXNlU2hpZWxkSURMaXN0Tm9uZRAAEg0K",
            "B0pld2VsSUQQwYQ9EgwKBkdvbGRJRBDChD0SEAoKSW50ZWdyYWxJRBDDhD0S",
            "DQoHUG93ZXJJRBCBiXoSEQoLRmF2b3JhYmxlSUQQjIl6Kk8KDEdvb2RzVXNl",
            "VHlwZRIUChBHb29kc1VzZVR5cGVOb25lEAASDQoJRXh0ZW5kQmFnEAUSCwoH",
            "R2l0ZkJveBAHEg0KCVZvaWNlVHlwZRAIKkcKDk1hbm9yU3RlYWxUeXBlEhYK",
            "Ek1hbm9yU3RlYWxUeXBlTm9uZRAAEgwKCENyb3BUeXBlEAESDwoLRGlnbGV0",
            "dFR5cGUQAipcCg5HdWVzc2luZ051bWJlchIQCgxHdWVzc2luZ05vbmUQABIR",
            "Cg1HdWVzc2luZ0ZpcnN0EAESEgoOR3Vlc3NpbmdTZWNvbmQQAhIRCg1HdWVz",
            "c2luZ1RoaXJkEAMqiAEKDkd1ZXNzaW5nU3RhdHVzEg4KClN0YXR1c05vbmUQ",
            "ABIQCgtTdGF0dXNTcGVlZBCRThITCg5TdGF0dXNTbG93RG93bhCSThIVChBT",
            "dGF0dXNJbnZpbmNpYmxlEJNOEhUKEFN0YXR1c0ltcHJpc29uZWQQlE4SEQoM",
            "U3RhdHVzRmluaXNoEJVOKnoKFVB1c2hOb3RpY2VHb29kc1NvdXJjZRIdChlQ",
            "dXNoTm90aWNlR29vZHNTb3VyY2VOb25lEAASFwoTWmlsbGlvbmFpcmVQdXNo",
            "VHlwZRABEhQKEE1hbm9yRGlnbGV0dFR5cGUQAhITCg9UcmVhc3VyZUJveFR5",
            "cGUQAypMChBQdXNoTm90aWNlU291cmNlEhgKFFB1c2hOb3RpY2VTb3VyY2VO",
            "b25lEAASDgoKU3lzdGVtVHlwZRABEg4KClBsYXllclR5cGUQAipUChFHZXRG",
            "YXZvcmFibGVTdGF0ZRIZChVHZXRGYXZvcmFibGVTdGF0ZU5vbmUQABIQCgxO",
            "ZXZlckdldFR5cGUQARISCg5BbHJlYWR5R2V0VHlwZRACKm4KCU1haWxTdGF0",
            "ZRIRCg1NYWlsU3RhdGVOb25lEAASDwoLVW5SZWFkU3RhdGUQARIUChBSZWFk",
            "QWxyZWFkeVN0YXRlEAISFgoSUmVhZFVuQWxyZWFkeVN0YXRlEAMSDwoLRGVs",
            "ZXRlU3RhdGUQBCpuCgxTaG9wSXRlbVR5cGUSFAoQU2hvcEl0ZW1UeXBlTm9u",
            "ZRAAEg0KCUNoYXJhY3RlchAFEhEKDVN0b3JlQ2xvdGhpbmcQBhIXChNQb2lu",
            "dHNTdG9yZUNsb3RoaW5nEAcSDQoJSGVhZEltYWdlEAgqSgoQU29pcmVlR2Ft",
            "ZVN0YXRlcxIYChRTb2lyZWVHYW1lU3RhdGVzTm9uZRAAEg0KCUJldFN0YXRl",
            "cxABEg0KCUdhbWVTdGF0ZRACKkUKCERpY2VUeXBlEhAKDERpY2VUeXBlTm9u",
            "ZRAAEgsKB0xvd0RpY2UQARIMCghIaWdoRGljZRACEgwKCFB1cmVEaWNlEAMq",
            "OAoJTHVja3lUeWVwEg0KCUx1Y2t5Tm9uZRAAEg0KCUx1Y2t5U2VlZBABEg0K",
            "CUx1Y2t5UHJvcBACKkUKCFRhc2tUeXBlEhAKDFRhc2tUeXBlTm9uZRAAEhQK",
            "EEd1aWRhbmNlVGFza1R5cGUQARIRCg1EYWlseVRhc2tUeXBlEAIqmwQKBlRh",
            "c2tJRBIOCgpUYXNrSUROb25lEAASDwoJTG9naW5UYXNrEKGcARIQCgpTaWdu",
            "SW5UYXNrEKKcARIZChNEYWlseUdldEltcHVsc2VUYXNrEKOcARIRCgtJbk1h",
            "bm9yVGFzaxCknAESDwoJUGxhbnRUYXNrEKWcARIRCgtIYXJ2ZXN0VGFzaxCm",
            "nAESFAoORmVydGlsaXplclRhc2sQp5wBEhQKDkRyZXNzTWFub3JUYXNrEKic",
            "ARITCg1TZWxsRnJ1aXRUYXNrEKmcARIWChBPcGVuT3JkaW5hcnlUYXNrEKqc",
            "ARIaChRPcGVuSW50ZXJtZWRpYXRlVGFzaxCrnAESFAoOT3BlblNlbmlvclRh",
            "c2sQrJwBEhYKEE1hbm9yRGlnbGV0dFRhc2sQrZwBEhwKFkZyaWVuZE1hbm9y",
            "RGlnbGV0dFRhc2sQrpwBEhIKDFVzZVBvd2VyVGFzaxCvnAESEwoNQ2F0Y2hE",
            "b2xsVGFzaxCwnAESFAoOR3Vlc3NCZWFuc1Rhc2sQsZwBEhYKEFdhdGNoU2Vj",
            "dGlvblRhc2sQspwBEh0KF1VuTG9ja0NpcmNsZUZyaWVuZHNUYXNrELOcARIS",
            "CgxTZW5kR2lmdFRhc2sQtJwBEhMKDUZpbmlzaExvd0RlYWwQtZwBEhYKEEZp",
            "bmlzaE1pZGRsZURlYWwQtpwBEhQKDkZpbmlzaEhpZ2hEZWFsELecASrIAgoJ",
            "R3VpZGVUYXNrEhEKDUd1aWRlVGFza05vbmUQABIOCglHdWlkZVNlZWQQk04S",
            "FAoPR3VpZGVGZXJ0aWxpemVyEJROEhEKDEd1aWRlSGFydmVzdBCVThITCg5H",
            "dWlkZVNlbGxGcnVpdBCYThIRCgxHdWlkZUJ1eVNlZWQQm04SDwoKR3VpZGVT",
            "dGVhbBCoThISCg1HdWlkZURlY29yYXRlEJJWEhYKEUd1aWRlTW92ZURlY29y",
            "YXRlEJNWEhIKDUd1aWRlTW92ZVNvaWwQlFYSEQoMR3VpZGVEaWdsZXR0EJVW",
            "EhAKC0d1aWRlUmFuZG9tEJZWEg0KCEd1aWRlTG93EJdWEg4KCUd1aWRlSGln",
            "aBCYVhIRCgxHdWlkZUNoYXB0ZXIQmVYSDgoJR3VpZGVBcmVhEJpWEg8KCkZp",
            "bmlzaERlYWwQm1YqZgoOV2FyZWhvdXNlQm94SUQSFgoSV2FyZWhvdXNlQm94",
            "SUROb25lEAASEgoLT3JkaW5hcnlCb3gQwY23ARIWCg9JbnRlcm1lZGlhdGVC",
            "b3gQwo23ARIQCglTZW5pb3JCb3gQw423ASqTAwoMT3BlbkZ1bmN0aW9uEgwK",
            "CE9wZW5Ob25lEAASDgoJT3Blbk1hbm9yEJFOEhIKDU9wZW5XYXJlaG91c2UQ",
            "kk4SEQoMT3Blbkd1aWRhbmNlEJNOEg0KCE9wZW5NYWlsEJROEhEKDE9wZW5V",
            "c2VySW5mbxCVThIUCg9PcGVuTG9iYnlGcmllbmQQlk4SEAoLT3BlbkNoYXB0",
            "ZXIQl04SDgoJT3BlblN0b3JlEJhOEhIKDU9wZW5Nb3ZlTWFub3IQmU4SEAoL",
            "T3BlbkRpZ2xldHQQmk4SEAoLT3BlblJpY2hNYW4Qm04SEQoMT3BlbkRlY29y",
            "YXRlEJxOEhQKD09wZW5NYW5vckZyaWVuZBCdThINCghPcGVuVGFzaxCeThIQ",
            "CgtPcGVuSW1wdWxzZRCfThIRCgxPcGVuQWN0aXZpdHkQoE4SEAoLT3BlbkV2",
            "ZW5pbmcQoU4SEQoMT3Blbk1hbm9yTG9nEKJOEhYKEU9wZW5PbmVLZXlIYXJ2",
            "ZXN0EKROEhIKDE9wZW5CdXlKZXdlbBChnAEqaAoMTWFpbENvbmZpZ0lEEhQK",
            "EE1haWxDb25maWdJRE5vbmUQABIQCgtSaWNoTWFuTWFpbBDpBxIOCglNYW5v",
            "ck1haWwQ6gcSDQoIR2lmdE1haWwQ6wcSEQoMV2FyZUhvdXNlQm94EOwHKowB",
            "Cg5NYWlsTG9jYWxpemVJRBIWChJNYWlsTG9jYWxpemVJRE5vbmUQABIeChZX",
            "YXJlaG91c2VGdWxsTWFpbFRpdGxlEIHz6JMBEiAKGFdhcmVob3VzZUZ1bGxN",
            "YWlsU3ViaGVhZBCCoMuYARIgChhXYXJlaG91c2VGdWxsTWFpbE1lc3NhZ2UQ",
            "g82tnQEqSgoIRGVhbFR5cGUSEAoMRGVhbFR5cGVOb25lEAASDAoITG93TGV2",
            "ZWwQARIPCgtNaWRkbGVMZXZlbBACEg0KCUhpZ2hMZXZlbBADKn8KDURlYWxB",
            "d2FyZFR5cGUSFQoRRGVhbEF3YXJkVHlwZU5vbmUQABIWChBEZWFsQXdhcmRK",
            "ZXdlbElEEMGEPRIVCg9EZWFsQXdhcmRHb2xkSUQQwoQ9EhQKDkRlYWxBd2Fy",
            "ZFdhdGVyEIWJehISCgxEZWFsQXdhcmRFeHAQhIl6YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Game.Protocal.ErrorCode), typeof(global::Game.Protocal.OpCodeType), typeof(global::Game.Protocal.ServerStatus), typeof(global::Game.Protocal.RegisterPlatform), typeof(global::Game.Protocal.manorMature), typeof(global::Game.Protocal.WebscoektError), typeof(global::Game.Protocal.ServerType), typeof(global::Game.Protocal.ManorScene), typeof(global::Game.Protocal.ConsumptionType), typeof(global::Game.Protocal.UnlockTreasureChest), typeof(global::Game.Protocal.PeriodGrow), typeof(global::Game.Protocal.AreaState), typeof(global::Game.Protocal.IsPromotion), typeof(global::Game.Protocal.GoodsBuyWay), typeof(global::Game.Protocal.WorkShedSpeedUpWay), typeof(global::Game.Protocal.WarehouseShieldIDList), typeof(global::Game.Protocal.GoodsUseType), typeof(global::Game.Protocal.ManorStealType), typeof(global::Game.Protocal.GuessingNumber), typeof(global::Game.Protocal.GuessingStatus), typeof(global::Game.Protocal.PushNoticeGoodsSource), typeof(global::Game.Protocal.PushNoticeSource), typeof(global::Game.Protocal.GetFavorableState), typeof(global::Game.Protocal.MailState), typeof(global::Game.Protocal.ShopItemType), typeof(global::Game.Protocal.SoireeGameStates), typeof(global::Game.Protocal.DiceType), typeof(global::Game.Protocal.LuckyTyep), typeof(global::Game.Protocal.TaskType), typeof(global::Game.Protocal.TaskID), typeof(global::Game.Protocal.GuideTask), typeof(global::Game.Protocal.WarehouseBoxID), typeof(global::Game.Protocal.OpenFunction), typeof(global::Game.Protocal.MailConfigID), typeof(global::Game.Protocal.MailLocalizeID), typeof(global::Game.Protocal.DealType), typeof(global::Game.Protocal.DealAwardType), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 错误码定义
  /// </summary>
  public enum ErrorCode {
    /// <summary>
    /// 未知错误
    /// </summary>
    [pbr::OriginalName("None")] None = 0,
    /// <summary>
    /// 成功
    /// </summary>
    [pbr::OriginalName("Success")] Success = 1,
    /// <summary>
    /// 操作码为空
    /// </summary>
    [pbr::OriginalName("OpCode_Null")] OpCodeNull = 2,
    /// <summary>
    /// 请求数据为空
    /// </summary>
    [pbr::OriginalName("Send_Data_Null")] SendDataNull = 2000,
    /// <summary>
    /// 解析数据异常
    /// </summary>
    [pbr::OriginalName("ServerReport_ServerReqDecodeFail")] ServerReportServerReqDecodeFail = 3000,
    /// <summary>
    /// mysql错误
    /// </summary>
    [pbr::OriginalName("Mysql_Error")] MysqlError = 4000,
    /// <summary>
    /// 请求失败没有对应方法
    /// </summary>
    [pbr::OriginalName("RequestError_NoMethod")] RequestErrorNoMethod = 4001,
    /// <summary>
    /// 服务器异常
    /// </summary>
    [pbr::OriginalName("ServerException")] ServerException = 4002,
    /// <summary>
    /// 请求必要信息为空
    /// </summary>
    [pbr::OriginalName("Request_Essential_Null")] RequestEssentialNull = 4003,
    /// <summary>
    /// 账户数据异常
    /// </summary>
    [pbr::OriginalName("Account_Abnormity")] AccountAbnormity = 10002,
    /// <summary>
    /// 新增用户失败
    /// </summary>
    [pbr::OriginalName("Account_Add_Error")] AccountAddError = 10003,
    /// <summary>
    /// 账户重复登录
    /// </summary>
    [pbr::OriginalName("Account_Repetition")] AccountRepetition = 10005,
    /// <summary>
    /// 唯一凭证为空
    /// </summary>
    [pbr::OriginalName("Account_Sole_Null")] AccountSoleNull = 10006,
    /// <summary>
    /// 没有这个用户
    /// </summary>
    [pbr::OriginalName("Account_Inexistence")] AccountInexistence = 10007,
    /// <summary>
    /// 设置账户名失败
    /// </summary>
    [pbr::OriginalName("Account_SetName_Error")] AccountSetNameError = 10008,
    /// <summary>
    /// 设置头像失败
    /// </summary>
    [pbr::OriginalName("Account_SetImage_Error")] AccountSetImageError = 10009,
    /// <summary>
    /// 获取用户大富翁地图信息失败
    /// </summary>
    [pbr::OriginalName("Account_Zillionaire_Map")] AccountZillionaireMap = 10013,
    /// <summary>
    /// 玩家暂时未获得大富翁这个地图
    /// </summary>
    [pbr::OriginalName("Account_Zillionaire_Acquire")] AccountZillionaireAcquire = 10014,
    /// <summary>
    /// 玩家该等级无升级奖励
    /// </summary>
    [pbr::OriginalName("Account_UpGrade_NoneAward")] AccountUpGradeNoneAward = 10015,
    /// <summary>
    /// 获取用户关联数据失败
    /// </summary>
    [pbr::OriginalName("Account_User_Config")] AccountUserConfig = 10016,
    /// <summary>
    /// 获取用户数据失败
    /// </summary>
    [pbr::OriginalName("Account_User_Info")] AccountUserInfo = 10017,
    /// <summary>
    /// 设置用户昵称重复
    /// </summary>
    [pbr::OriginalName("Account_SetName_Repetition")] AccountSetNameRepetition = 10018,
    /// <summary>
    /// 没有对应的头像信息
    /// </summary>
    [pbr::OriginalName("Account_Image_Config")] AccountImageConfig = 10019,
    /// <summary>
    /// 未获得头像
    /// </summary>
    [pbr::OriginalName("Account_No_Image")] AccountNoImage = 10020,
    /// <summary>
    /// 获取头像信息失败
    /// </summary>
    [pbr::OriginalName("Account_Image_Info")] AccountImageInfo = 10021,
    /// <summary>
    /// 注销账号失败
    /// </summary>
    [pbr::OriginalName("Account_Logout_Error")] AccountLogoutError = 10022,
    /// <summary>
    /// 添加好友失败
    /// </summary>
    [pbr::OriginalName("Friend_Add_Fail")] FriendAddFail = 20004,
    /// <summary>
    /// 重复添加好友申请
    /// </summary>
    [pbr::OriginalName("Friend_Add_Again")] FriendAddAgain = 20005,
    /// <summary>
    /// 删除好友失败
    /// </summary>
    [pbr::OriginalName("Friend_Del_Fail")] FriendDelFail = 20006,
    /// <summary>
    /// 搜索好友为空
    /// </summary>
    [pbr::OriginalName("Friend_Search_Fail")] FriendSearchFail = 200007,
    /// <summary>
    /// 好友上限
    /// </summary>
    [pbr::OriginalName("Friend_Max")] FriendMax = 200008,
    /// <summary>
    /// 玩家不存在
    /// </summary>
    [pbr::OriginalName("User_Not_Existent")] UserNotExistent = 200010,
    /// <summary>
    /// 拒绝添加好友失败
    /// </summary>
    [pbr::OriginalName("Friend_Refuse_Add")] FriendRefuseAdd = 200013,
    /// <summary>
    /// 大富翁
    /// 没有请求的地图信息
    /// </summary>
    [pbr::OriginalName("Map_Inexistence")] MapInexistence = 200100,
    /// <summary>
    /// 地图重复购买
    /// </summary>
    [pbr::OriginalName("Map_Repetition_Buy")] MapRepetitionBuy = 200102,
    /// <summary>
    /// 体力不够了
    /// </summary>
    [pbr::OriginalName("Map_PhysicalPower_Insufficient")] MapPhysicalPowerInsufficient = 200103,
    /// <summary>
    /// 本次游戏购买次数上限
    /// </summary>
    [pbr::OriginalName("Map_Purchase_Limit")] MapPurchaseLimit = 200105,
    /// <summary>
    /// 购买角色不存在
    /// </summary>
    [pbr::OriginalName("Map_Role_Inexistence")] MapRoleInexistence = 200107,
    /// <summary>
    /// 购买角色失败
    /// </summary>
    [pbr::OriginalName("Map_Role_defeated")] MapRoleDefeated = 200108,
    /// <summary>
    /// 生成大富翁奖励失败
    /// </summary>
    [pbr::OriginalName("Map_Award_Defeated")] MapAwardDefeated = 200109,
    /// <summary>
    /// 记录奖励信息失败
    /// </summary>
    [pbr::OriginalName("Map_Record_Award")] MapRecordAward = 200110,
    /// <summary>
    /// 购买地图失败
    /// </summary>
    [pbr::OriginalName("Map_Buy_Defeated")] MapBuyDefeated = 200113,
    /// <summary>
    /// 选择角色失败
    /// </summary>
    [pbr::OriginalName("Map_Choice_Defeated")] MapChoiceDefeated = 200114,
    /// <summary>
    /// 当前种植地上限
    /// </summary>
    [pbr::OriginalName("Map_Plant_Limit")] MapPlantLimit = 200115,
    /// <summary>
    /// 进入大富翁使用次数完
    /// </summary>
    [pbr::OriginalName("Map_Count_Finish")] MapCountFinish = 200118,
    /// <summary>
    /// 扣除大富翁次数失败
    /// </summary>
    [pbr::OriginalName("Map_Count_Deduct")] MapCountDeduct = 200119,
    /// <summary>
    /// 请选择骰子类型
    /// </summary>
    [pbr::OriginalName("Map_Dice_Type")] MapDiceType = 200120,
    /// <summary>
    /// 骰子失败
    /// </summary>
    [pbr::OriginalName("Map_Dice_Defeated")] MapDiceDefeated = 200121,
    /// <summary>
    /// 请选择抽奖类型
    /// </summary>
    [pbr::OriginalName("Map_Lucky_Type")] MapLuckyType = 200122,
    /// <summary>
    /// 不在抽道具位置
    /// </summary>
    [pbr::OriginalName("Map_Lucky_Prop")] MapLuckyProp = 200123,
    /// <summary>
    /// 不在抽种子位置
    /// </summary>
    [pbr::OriginalName("Map_Lucky_Seed")] MapLuckySeed = 200124,
    /// <summary>
    /// 抽奖次数已用户
    /// </summary>
    [pbr::OriginalName("Map_Lucky_Count")] MapLuckyCount = 200125,
    /// <summary>
    /// 获取奖励失败
    /// </summary>
    [pbr::OriginalName("Map_Lucky_Defeated")] MapLuckyDefeated = 200126,
    /// <summary>
    /// 庄园
    /// 拖拽失败
    /// </summary>
    [pbr::OriginalName("Manor_Drag_Defeated")] ManorDragDefeated = 203000,
    /// <summary>
    /// 提前铲除种植物失败
    /// </summary>
    [pbr::OriginalName("Manor_Eradicate_Defeated")] ManorEradicateDefeated = 203002,
    /// <summary>
    /// 交换位置失败
    /// </summary>
    [pbr::OriginalName("Manor_Change_Position")] ManorChangePosition = 203004,
    /// <summary>
    /// 没有需要收获的
    /// </summary>
    [pbr::OriginalName("Manor_Harvest")] ManorHarvest = 203005,
    /// <summary>
    /// 种植数据为空
    /// </summary>
    [pbr::OriginalName("Manor_Plant_Null")] ManorPlantNull = 203006,
    /// <summary>
    /// 查询玩家没有信息
    /// </summary>
    [pbr::OriginalName("Manor_None_Info")] ManorNoneInfo = 203007,
    /// <summary>
    /// 作物已成熟不能使用化肥
    /// </summary>
    [pbr::OriginalName("Manor_Crop_Adultness")] ManorCropAdultness = 203008,
    /// <summary>
    /// 化肥使用失败
    /// </summary>
    [pbr::OriginalName("Manor_Use_Fertilizer")] ManorUseFertilizer = 203010,
    /// <summary>
    /// 没有这个地块信息
    /// </summary>
    [pbr::OriginalName("Manor_Parcel_Info")] ManorParcelInfo = 203011,
    /// <summary>
    /// 回收的类型不是装饰物
    /// </summary>
    [pbr::OriginalName("Manor_Recycle_Decorate")] ManorRecycleDecorate = 203014,
    /// <summary>
    /// 当前这块地不在种植中
    /// </summary>
    [pbr::OriginalName("Manor_No_Plant")] ManorNoPlant = 203015,
    /// <summary>
    /// 移除装饰物失败
    /// </summary>
    [pbr::OriginalName("Manor_Remove_Defeated")] ManorRemoveDefeated = 203016,
    /// <summary>
    /// 收获失败
    /// </summary>
    [pbr::OriginalName("Manor_Harvest_Defeated")] ManorHarvestDefeated = 203017,
    /// <summary>
    /// 扣除玩家农作物失败
    /// </summary>
    [pbr::OriginalName("Manor_Deduct_Goods")] ManorDeductGoods = 203018,
    /// <summary>
    /// 不能偷取自己
    /// </summary>
    [pbr::OriginalName("Manor_Steal_Oneself")] ManorStealOneself = 203020,
    /// <summary>
    /// 没有可以偷取的作物
    /// </summary>
    [pbr::OriginalName("Manor_Steal_No")] ManorStealNo = 203021,
    /// <summary>
    /// 没有对应解锁信息
    /// </summary>
    [pbr::OriginalName("Manor_Unlock_Info")] ManorUnlockInfo = 203023,
    /// <summary>
    /// 作物已被收获了
    /// </summary>
    [pbr::OriginalName("Manor_Harvest_Finish")] ManorHarvestFinish = 203025,
    /// <summary>
    /// 作物不能在偷取了
    /// </summary>
    [pbr::OriginalName("Manor_Harvest_Lateness")] ManorHarvestLateness = 203026,
    /// <summary>
    /// 新增解锁区域失败
    /// </summary>
    [pbr::OriginalName("Manor_New_Defeated")] ManorNewDefeated = 203027,
    /// <summary>
    /// 修改区域状态信息失败
    /// </summary>
    [pbr::OriginalName("Manor_Area_State")] ManorAreaState = 203028,
    /// <summary>
    /// 获取区域状态信息失败
    /// </summary>
    [pbr::OriginalName("Manor_Acquire_Area")] ManorAcquireArea = 203029,
    /// <summary>
    /// 当前在施工阶段
    /// </summary>
    [pbr::OriginalName("Manor_Roadwork_Stage")] ManorRoadworkStage = 203030,
    /// <summary>
    /// 当前不能施工加速
    /// </summary>
    [pbr::OriginalName("Manor_Roadwork_Speed")] ManorRoadworkSpeed = 203031,
    /// <summary>
    /// 庄园宝箱解锁钥匙不足
    /// </summary>
    [pbr::OriginalName("Manor_Key_Notenough")] ManorKeyNotenough = 203034,
    /// <summary>
    /// 回收地块道具失败
    /// </summary>
    [pbr::OriginalName("Manor_Recycle_Error")] ManorRecycleError = 203035,
    /// <summary>
    /// 宝箱解锁时间异常
    /// </summary>
    [pbr::OriginalName("Manor_BoxUnlock_Time")] ManorBoxUnlockTime = 203036,
    /// <summary>
    /// 宝箱还在解锁中
    /// </summary>
    [pbr::OriginalName("Manor_Box_Unlock")] ManorBoxUnlock = 203037,
    /// <summary>
    /// 回收宝箱失败
    /// </summary>
    [pbr::OriginalName("Manor_Box_Recycle")] ManorBoxRecycle = 203038,
    /// <summary>
    /// 选择的不是宝箱
    /// </summary>
    [pbr::OriginalName("Manor_No_Box")] ManorNoBox = 203039,
    /// <summary>
    /// 宝箱已处理领域状态了
    /// </summary>
    [pbr::OriginalName("Manor_Box_Get")] ManorBoxGet = 203040,
    /// <summary>
    /// 更新宝箱解锁时间错误
    /// </summary>
    [pbr::OriginalName("Manor_Box_UpdateUnlockTIme")] ManorBoxUpdateUnlockTime = 203041,
    /// <summary>
    /// 今日地鼠奖励次数上限
    /// </summary>
    [pbr::OriginalName("Manor_Diglett_NumMax")] ManorDiglettNumMax = 203042,
    /// <summary>
    /// 获取地鼠奖励失败
    /// </summary>
    [pbr::OriginalName("Manor_DiglettWarad_Error")] ManorDiglettWaradError = 203043,
    /// <summary>
    /// 已经抓过该好友庄园地鼠
    /// </summary>
    [pbr::OriginalName("Manor_FriendManorDiglett_Again")] ManorFriendManorDiglettAgain = 203044,
    /// <summary>
    /// 请求异常不允许在好友庄园领取自己庄园地鼠
    /// </summary>
    [pbr::OriginalName("Manor_FriendDiglett_Myself")] ManorFriendDiglettMyself = 203045,
    /// <summary>
    /// 偷取日志记录失败
    /// </summary>
    [pbr::OriginalName("Manor_StealLog_Error")] ManorStealLogError = 203046,
    /// <summary>
    /// 拖拽的不是装饰物
    /// </summary>
    [pbr::OriginalName("Manor_ManorDrag_NoDecorate")] ManorManorDragNoDecorate = 203047,
    /// <summary>
    /// 庄园看广告加速次数已用完
    /// </summary>
    [pbr::OriginalName("Manor_Free_Number")] ManorFreeNumber = 203048,
    /// <summary>
    /// 庄园看广告加速失败
    /// </summary>
    [pbr::OriginalName("Manor_Free_Defeated")] ManorFreeDefeated = 203049,
    /// <summary>
    /// 该作物不能购买
    /// </summary>
    [pbr::OriginalName("Manor_ThisCrop_DonTBuy")] ManorThisCropDonTbuy = 203050,
    /// <summary>
    /// 装饰物旋转失败
    /// </summary>
    [pbr::OriginalName("Manor_DecorateRotate_Error")] ManorDecorateRotateError = 203051,
    /// <summary>
    /// 水滴为空
    /// </summary>
    [pbr::OriginalName("Manor_Water_Null")] ManorWaterNull = 203052,
    /// <summary>
    /// 使用水滴失败
    /// </summary>
    [pbr::OriginalName("Manor_Use_Water")] ManorUseWater = 203053,
    /// <summary>
    /// 道具
    /// 道具ID错误
    /// </summary>
    [pbr::OriginalName("Good_Id_Error")] GoodIdError = 205001,
    /// <summary>
    /// 购买失败消耗道具不足
    /// </summary>
    [pbr::OriginalName("Good_Consume")] GoodConsume = 205002,
    /// <summary>
    /// 道具更新失败
    /// </summary>
    [pbr::OriginalName("Good_Update_Error")] GoodUpdateError = 205004,
    /// <summary>
    /// 道具锁定失败
    /// </summary>
    [pbr::OriginalName("Good_Lock_Error")] GoodLockError = 205006,
    /// <summary>
    /// 出售失败
    /// </summary>
    [pbr::OriginalName("Good_Sell_Error")] GoodSellError = 205007,
    /// <summary>
    /// 获取金币钻石失败
    /// </summary>
    [pbr::OriginalName("Good_Goldjewel_Error")] GoodGoldjewelError = 205009,
    /// <summary>
    /// 钻石不足
    /// </summary>
    [pbr::OriginalName("Good_Jewel_Insufficient")] GoodJewelInsufficient = 205010,
    /// <summary>
    /// 配置异常
    /// </summary>
    [pbr::OriginalName("Store_Config_Error")] StoreConfigError = 205011,
    /// <summary>
    /// 钻石对换金币失败
    /// </summary>
    [pbr::OriginalName("Jewel_Trade_Gold")] JewelTradeGold = 205012,
    /// <summary>
    /// 扣除钻石失败
    /// </summary>
    [pbr::OriginalName("Good_Reducejewel_Error")] GoodReducejewelError = 205013,
    /// <summary>
    /// 仓库空间不足
    /// </summary>
    [pbr::OriginalName("Good_Warehouse_Insufficient")] GoodWarehouseInsufficient = 205014,
    /// <summary>
    /// 购买失败当前道具未解锁
    /// </summary>
    [pbr::OriginalName("Good_Goodslock_Error")] GoodGoodslockError = 205015,
    /// <summary>
    /// 购买上限
    /// </summary>
    [pbr::OriginalName("Good_Buygoods_Max")] GoodBuygoodsMax = 205016,
    /// <summary>
    /// 扣除道具失败
    /// </summary>
    [pbr::OriginalName("Good_Deduct_Defeated")] GoodDeductDefeated = 205018,
    /// <summary>
    /// 没有购买的道具信息
    /// </summary>
    [pbr::OriginalName("Good_No_Info")] GoodNoInfo = 205019,
    /// <summary>
    /// 道具入库失败
    /// </summary>
    [pbr::OriginalName("Godd_Storage_Defeated")] GoddStorageDefeated = 205021,
    /// <summary>
    /// 道具配置异常
    /// </summary>
    [pbr::OriginalName("Good_Config_Error")] GoodConfigError = 205022,
    /// <summary>
    /// 已超过购买时间
    /// </summary>
    [pbr::OriginalName("Good_BuyTime_Exceed")] GoodBuyTimeExceed = 205023,
    /// <summary>
    /// 邮件
    /// 附件领取失败
    /// </summary>
    [pbr::OriginalName("Mail_Getaccessory_Error")] MailGetaccessoryError = 206001,
    /// <summary>
    /// 获取附件失败
    /// </summary>
    [pbr::OriginalName("Mail_Getaccessory_Defeated")] MailGetaccessoryDefeated = 206002,
    /// <summary>
    /// 更改邮件状态失败
    /// </summary>
    [pbr::OriginalName("Mail_ChangeMailState_Error")] MailChangeMailStateError = 206004,
    /// <summary>
    /// 章节
    /// 章节解锁失败
    /// </summary>
    [pbr::OriginalName("Seciton_Unlock_Error")] SecitonUnlockError = 207002,
    /// <summary>
    /// 购买番外剧情失败紫星币不足
    /// </summary>
    [pbr::OriginalName("ExtraStory_Zixingbi_Insufficient")] ExtraStoryZixingbiInsufficient = 207003,
    /// <summary>
    /// 紫星币扣除失败
    /// </summary>
    [pbr::OriginalName("ExtraStory_Zixingbi_Error")] ExtraStoryZixingbiError = 207004,
    /// <summary>
    /// 购买番外剧情失败
    /// </summary>
    [pbr::OriginalName("BuyExtraStory_Error")] BuyExtraStoryError = 207005,
    /// <summary>
    /// 没有购买章节信息
    /// </summary>
    [pbr::OriginalName("Section_Buy_Info")] SectionBuyInfo = 207007,
    /// <summary>
    /// 没有购买的番外信息
    /// </summary>
    [pbr::OriginalName("Section_Extra_Info")] SectionExtraInfo = 207008,
    /// <summary>
    /// 章节通关异常
    /// </summary>
    [pbr::OriginalName("Section_Clearance_Error")] SectionClearanceError = 207009,
    /// <summary>
    /// 章节重复购买
    /// </summary>
    [pbr::OriginalName("Section_Repetition_Buy")] SectionRepetitionBuy = 207010,
    /// <summary>
    /// 购买的不是下一章节
    /// </summary>
    [pbr::OriginalName("Section_Buy_Next")] SectionBuyNext = 207011,
    /// <summary>
    /// 新章节暂时未开放
    /// </summary>
    [pbr::OriginalName("Section_New_Open")] SectionNewOpen = 207012,
    /// <summary>
    /// 仓库
    /// 获取仓库数据失败
    /// </summary>
    [pbr::OriginalName("Warehouse_Detail_Defeated")] WarehouseDetailDefeated = 208001,
    /// <summary>
    /// 获取宝箱信息错误
    /// </summary>
    [pbr::OriginalName("Warehouse_BoxInfo_Error")] WarehouseBoxInfoError = 208004,
    /// <summary>
    /// 宝箱钥匙不足
    /// </summary>
    [pbr::OriginalName("WareHouse_BoxKey_NotEnough")] WareHouseBoxKeyNotEnough = 208005,
    /// <summary>
    /// 宝箱解锁失败
    /// </summary>
    [pbr::OriginalName("WareHouse_BoxUnlock_Error")] WareHouseBoxUnlockError = 208006,
    /// <summary>
    /// 宝箱尚未解锁完成
    /// </summary>
    [pbr::OriginalName("WareHouse_BoxUnlockTime_NotEnough")] WareHouseBoxUnlockTimeNotEnough = 208007,
    /// <summary>
    /// 更改宝箱解锁信息失败
    /// </summary>
    [pbr::OriginalName("WareHouse_UpdateBoxUnlockInfo_Error")] WareHouseUpdateBoxUnlockInfoError = 208009,
    /// <summary>
    /// 扣除宝箱数量失败
    /// </summary>
    [pbr::OriginalName("WareHouse_DelBoxNum_Error")] WareHouseDelBoxNumError = 208010,
    /// <summary>
    /// 仓库宝箱加速失败
    /// </summary>
    [pbr::OriginalName("WareHouse_BoxSpeed_Failure")] WareHouseBoxSpeedFailure = 208011,
    /// <summary>
    /// 仓库礼盒配置信息有误
    /// </summary>
    [pbr::OriginalName("WareHouse_GitfBoxInfo_Error")] WareHouseGitfBoxInfoError = 208014,
    /// <summary>
    /// 仓库道具使用失败
    /// </summary>
    [pbr::OriginalName("WareHouse_UseGoods_Error")] WareHouseUseGoodsError = 208018,
    /// <summary>
    /// 配置
    /// 没有对应Id的配置信息
    /// </summary>
    [pbr::OriginalName("Config_No_Info")] ConfigNoInfo = 209001,
    /// <summary>
    /// 广告加速请求时间过短
    /// </summary>
    [pbr::OriginalName("Advertising_Speed_Anomaly")] AdvertisingSpeedAnomaly = 209002,
    /// <summary>
    /// 签到
    /// 签到失败
    /// </summary>
    [pbr::OriginalName("Sign_In_Fail")] SignInFail = 209500,
    /// <summary>
    /// 获取签单信息失败
    /// </summary>
    [pbr::OriginalName("Sign_Accumulate_Fail")] SignAccumulateFail = 209501,
    /// <summary>
    /// 没有达到累积签到信息
    /// </summary>
    [pbr::OriginalName("Sign_Accumulate_Enough")] SignAccumulateEnough = 209502,
    /// <summary>
    /// 没有累积签到奖励
    /// </summary>
    [pbr::OriginalName("Sign_Accumulate_Award")] SignAccumulateAward = 209503,
    /// <summary>
    /// 领取累积奖励失败
    /// </summary>
    [pbr::OriginalName("Sign_Award_Fail")] SignAwardFail = 209504,
    /// <summary>
    /// 每日签到重复签到
    /// </summary>
    [pbr::OriginalName("Sign_Everyday_Repetition")] SignEverydayRepetition = 209505,
    /// <summary>
    /// 发送的消息为空
    /// </summary>
    [pbr::OriginalName("Send_Message_Null")] SendMessageNull = 300001,
    /// <summary>
    /// 心动时刻
    /// 获取配置失败
    /// </summary>
    [pbr::OriginalName("Impulse_GetConfig_Error")] ImpulseGetConfigError = 400001,
    /// <summary>
    /// 赠送礼物失败
    /// </summary>
    [pbr::OriginalName("Impulse_Send_Gift_Error")] ImpulseSendGiftError = 400004,
    /// <summary>
    /// 章节增加好感度失败
    /// </summary>
    [pbr::OriginalName("Impulse_Section_Option_Error")] ImpulseSectionOptionError = 400005,
    /// <summary>
    /// 章节选项记录添加失败
    /// </summary>
    [pbr::OriginalName("Impulse_Add_Section_Optioned")] ImpulseAddSectionOptioned = 400006,
    /// <summary>
    /// 领取登录好感值失败
    /// </summary>
    [pbr::OriginalName("Impulse_GetLoginFavorable_Error")] ImpulseGetLoginFavorableError = 400007,
    /// <summary>
    /// 已领取当前章节好感值
    /// </summary>
    [pbr::OriginalName("Impulse_Section_Favorable_Again")] ImpulseSectionFavorableAgain = 400008,
    /// <summary>
    /// 晚会
    /// 房间列表为空
    /// </summary>
    [pbr::OriginalName("Section_Room_Null")] SectionRoomNull = 500001,
    /// <summary>
    /// 房间异常
    /// </summary>
    [pbr::OriginalName("Section_Room_Abnormity")] SectionRoomAbnormity = 500002,
    /// <summary>
    /// 房间上限
    /// </summary>
    [pbr::OriginalName("Section_Room_Limit")] SectionRoomLimit = 500003,
    /// <summary>
    /// 你当前不在房间内
    /// </summary>
    [pbr::OriginalName("Section_Absent_Room")] SectionAbsentRoom = 500004,
    /// <summary>
    /// 暂时不能领取经验
    /// </summary>
    [pbr::OriginalName("Section_No_Receive")] SectionNoReceive = 500005,
    /// <summary>
    /// 竞猜请求数据为空
    /// </summary>
    [pbr::OriginalName("Section_Guessing_Null")] SectionGuessingNull = 500006,
    /// <summary>
    /// 移动位置失败
    /// </summary>
    [pbr::OriginalName("Section_Move_Position")] SectionMovePosition = 500007,
    /// <summary>
    /// 当前不在下注时间
    /// </summary>
    [pbr::OriginalName("Section_BetTime_Error")] SectionBetTimeError = 500008,
    /// <summary>
    /// 活动暂未开启或以结束
    /// </summary>
    [pbr::OriginalName("Section_IsEndOrNotOpen")] SectionIsEndOrNotOpen = 500009,
    /// <summary>
    /// 角色
    /// 已拥有这个角色
    /// </summary>
    [pbr::OriginalName("Role_IsOwn")] RoleIsOwn = 600001,
    /// <summary>
    /// 该角色不在配置表中
    /// </summary>
    [pbr::OriginalName("Role_Config_DontExist")] RoleConfigDontExist = 600002,
    /// <summary>
    /// 切换角色失败
    /// </summary>
    [pbr::OriginalName("Role_SwitchRole_Error")] RoleSwitchRoleError = 600005,
    /// <summary>
    /// 服饰修改失败
    /// </summary>
    [pbr::OriginalName("Role_HallUpdate_Error")] RoleHallUpdateError = 600006,
    /// <summary>
    /// 角色列表获取失败
    /// </summary>
    [pbr::OriginalName("Role_List_Defeated")] RoleListDefeated = 600007,
    /// <summary>
    /// 新增角色失败
    /// </summary>
    [pbr::OriginalName("Role_Add_Defeated")] RoleAddDefeated = 600008,
    /// <summary>
    /// 没有服饰信息
    /// </summary>
    [pbr::OriginalName("Role_Costume_Info")] RoleCostumeInfo = 600009,
    /// <summary>
    /// 更新服饰失败
    /// </summary>
    [pbr::OriginalName("Role_Costume_Renewal")] RoleCostumeRenewal = 600010,
    /// <summary>
    /// 引导
    /// 保存引导失败
    /// </summary>
    [pbr::OriginalName("Guidance_Save_Defeated")] GuidanceSaveDefeated = 650001,
    /// <summary>
    /// 引导异常
    /// </summary>
    [pbr::OriginalName("Guidance_Abnormal")] GuidanceAbnormal = 650002,
    /// <summary>
    /// 已完成引导
    /// </summary>
    [pbr::OriginalName("Guidance_Finish")] GuidanceFinish = 650003,
    /// <summary>
    /// 没有对应的引导id
    /// </summary>
    [pbr::OriginalName("Guidance_No_Info")] GuidanceNoInfo = 650004,
    /// <summary>
    /// 任务
    /// 领取任务奖励失败
    /// </summary>
    [pbr::OriginalName("Task_GetAward_Error")] TaskGetAwardError = 700001,
    /// <summary>
    /// 领取任务经验奖励失败
    /// </summary>
    [pbr::OriginalName("Task_GetTaskExperience_Error")] TaskGetTaskExperienceError = 700002,
    /// <summary>
    /// 功能未开放
    /// </summary>
    [pbr::OriginalName("Function_IsNotOpen")] FunctionIsNotOpen = 800001,
    /// <summary>
    /// 任务订单
    /// 暂无可提交任务订单
    /// </summary>
    [pbr::OriginalName("Deal_CurrentNotDealSubmit")] DealCurrentNotDealSubmit = 900001,
    /// <summary>
    /// 当前提交任务错误
    /// </summary>
    [pbr::OriginalName("Deal_CurrentSubMit_Error")] DealCurrentSubMitError = 900002,
    /// <summary>
    /// 提交订单失败
    /// </summary>
    [pbr::OriginalName("Deal_Submit_Error")] DealSubmitError = 900003,
    /// <summary>
    /// 刷新订单异常
    /// </summary>
    [pbr::OriginalName("Deal_Refresh_Error")] DealRefreshError = 900004,
    /// <summary>
    /// 暂无订单数据
    /// </summary>
    [pbr::OriginalName("Deal_DataIsNull")] DealDataIsNull = 900005,
    /// <summary>
    /// 跳过订单冷却失败
    /// </summary>
    [pbr::OriginalName("Deal_SkipDealAdv_Error")] DealSkipDealAdvError = 900006,
    /// <summary>
    /// 领取经验失败
    /// </summary>
    [pbr::OriginalName("Deal_GetExp_Error")] DealGetExpError = 900007,
    /// <summary>
    /// 该订单还在冷却中
    /// </summary>
    [pbr::OriginalName("Deal_OnCDTime")] DealOnCdtime = 900008,
  }

  /// <summary>
  /// 请求操作类型码
  /// </summary>
  public enum OpCodeType {
    [pbr::OriginalName("OpCodeTypeNone")] None = 0,
    /// <summary>
    /// 获取连接服务器信息和登录注册功能
    /// </summary>
    [pbr::OriginalName("LoadBalance")] LoadBalance = 1,
    /// <summary>
    /// 登录注册
    /// </summary>
    [pbr::OriginalName("AccountInfo")] AccountInfo = 2,
    /// <summary>
    /// 设置用户头像,昵称
    /// </summary>
    [pbr::OriginalName("BasicsInfo")] BasicsInfo = 3,
    /// <summary>
    /// 获取连接服务器信息
    /// </summary>
    [pbr::OriginalName("GetConnectServer")] GetConnectServer = 4,
    /// <summary>
    /// 获取好友列表
    /// </summary>
    [pbr::OriginalName("GetFriendList")] GetFriendList = 5,
    /// <summary>
    /// 获取申请列表
    /// </summary>
    [pbr::OriginalName("GetApplyList")] GetApplyList = 6,
    /// <summary>
    /// 获取推荐列表
    /// </summary>
    [pbr::OriginalName("GetReferralsList")] GetReferralsList = 7,
    /// <summary>
    /// 申请添加
    /// </summary>
    [pbr::OriginalName("ApplyAdd")] ApplyAdd = 8,
    /// <summary>
    /// 接收添加
    /// </summary>
    [pbr::OriginalName("AcceptAdd")] AcceptAdd = 9,
    /// <summary>
    /// 拒绝添加
    /// </summary>
    [pbr::OriginalName("RepulseAdd")] RepulseAdd = 10,
    /// <summary>
    /// 删除好友
    /// </summary>
    [pbr::OriginalName("DelFriend")] DelFriend = 11,
    /// <summary>
    /// 搜索
    /// </summary>
    [pbr::OriginalName("SearchUser")] SearchUser = 12,
    /// <summary>
    /// 选择进入大富翁地图
    /// </summary>
    [pbr::OriginalName("EnterRichManMap")] EnterRichManMap = 13,
    /// <summary>
    /// 筛子
    /// </summary>
    [pbr::OriginalName("RichManDice")] RichManDice = 14,
    /// <summary>
    /// 大富翁结束
    /// </summary>
    [pbr::OriginalName("RichManFinish")] RichManFinish = 15,
    /// <summary>
    /// 大富翁抽道具或种子
    /// </summary>
    [pbr::OriginalName("RichLucky")] RichLucky = 16,
    /// <summary>
    /// 广告作物加速
    /// </summary>
    [pbr::OriginalName("CropSpeed")] CropSpeed = 17,
    /// <summary>
    /// 购买道具
    /// </summary>
    [pbr::OriginalName("BuyProp")] BuyProp = 18,
    /// <summary>
    /// 拖拽创建道具
    /// </summary>
    [pbr::OriginalName("Drag")] Drag = 19,
    /// <summary>
    /// 获取庄园信息
    /// </summary>
    [pbr::OriginalName("GetManorInfo")] GetManorInfo = 20,
    /// <summary>
    /// 使用化肥
    /// </summary>
    [pbr::OriginalName("Fertilizer")] Fertilizer = 21,
    /// <summary>
    /// 提前铲除
    /// </summary>
    [pbr::OriginalName("Eradicate")] Eradicate = 22,
    /// <summary>
    /// 播种
    /// </summary>
    [pbr::OriginalName("Plant")] Plant = 23,
    /// <summary>
    /// 收获
    /// </summary>
    [pbr::OriginalName("Harvest")] Harvest = 24,
    /// <summary>
    /// 偷取
    /// </summary>
    [pbr::OriginalName("Steal")] Steal = 25,
    /// <summary>
    /// 交换位置
    /// </summary>
    [pbr::OriginalName("ChangeLocation")] ChangeLocation = 26,
    /// <summary>
    /// 仓库道具出售
    /// </summary>
    [pbr::OriginalName("GoodSell")] GoodSell = 27,
    /// <summary>
    /// 道具锁定
    /// </summary>
    [pbr::OriginalName("GoodLock")] GoodLock = 28,
    /// <summary>
    /// 查询其它人庄园信息
    /// </summary>
    [pbr::OriginalName("QueryOtherManor")] QueryOtherManor = 29,
    /// <summary>
    /// 解锁大区域
    /// </summary>
    [pbr::OriginalName("UnlockArea")] UnlockArea = 30,
    /// <summary>
    /// 获取角色列表(大富翁)
    /// </summary>
    [pbr::OriginalName("GetRoleList")] GetRoleList = 31,
    /// <summary>
    /// 选择角色(大富翁)
    /// </summary>
    [pbr::OriginalName("ChoiceRole")] ChoiceRole = 32,
    /// <summary>
    /// 购买角色(大富翁)
    /// </summary>
    [pbr::OriginalName("BuyRole")] BuyRole = 33,
    /// <summary>
    /// 获取限购信息
    /// </summary>
    [pbr::OriginalName("PromotionsGoodsInfo")] PromotionsGoodsInfo = 34,
    /// <summary>
    /// 金币钻石购买
    /// </summary>
    [pbr::OriginalName("GoldJewel")] GoldJewel = 35,
    /// <summary>
    /// 章节购买
    /// </summary>
    [pbr::OriginalName("BuySection")] BuySection = 36,
    /// <summary>
    /// 章节通关
    /// </summary>
    [pbr::OriginalName("ClearanceStcion")] ClearanceStcion = 37,
    /// <summary>
    /// 装饰物收回
    /// </summary>
    [pbr::OriginalName("OrnamentalRecycle")] OrnamentalRecycle = 38,
    /// <summary>
    /// 使用仓库宝箱
    /// </summary>
    [pbr::OriginalName("TreasureChest")] TreasureChest = 39,
    /// <summary>
    /// 领取宝箱奖励
    /// </summary>
    [pbr::OriginalName("TreasureChestAward")] TreasureChestAward = 40,
    /// <summary>
    /// 庄园宝箱解锁
    /// </summary>
    [pbr::OriginalName("ManorBox")] ManorBox = 41,
    /// <summary>
    /// 领取庄园宝箱
    /// </summary>
    [pbr::OriginalName("ClickManorBox")] ClickManorBox = 42,
    /// <summary>
    /// 购买番外剧情
    /// </summary>
    [pbr::OriginalName("BuyExtraStory")] BuyExtraStory = 43,
    /// <summary>
    /// 获取邮件
    /// </summary>
    [pbr::OriginalName("GetMail")] GetMail = 44,
    /// <summary>
    /// 获取附件
    /// </summary>
    [pbr::OriginalName("GetAccessory")] GetAccessory = 45,
    /// <summary>
    /// 根据邮件id获取附件信息
    /// </summary>
    [pbr::OriginalName("GetAccessoryInfo")] GetAccessoryInfo = 46,
    /// <summary>
    /// 每日签到
    /// </summary>
    [pbr::OriginalName("SignIn")] SignIn = 47,
    /// <summary>
    /// 获取好友列表庄园成熟信息
    /// </summary>
    [pbr::OriginalName("FriendManor")] FriendManor = 49,
    /// <summary>
    /// 玩家升级
    /// </summary>
    [pbr::OriginalName("UserUpGrage")] UserUpGrage = 50,
    /// <summary>
    /// 宝箱解锁加速
    /// </summary>
    [pbr::OriginalName("BoxSpeedUp")] BoxSpeedUp = 52,
    /// <summary>
    /// 工棚施工加速
    /// </summary>
    [pbr::OriginalName("WorkShedSpeedUp")] WorkShedSpeedUp = 53,
    /// <summary>
    /// 获取仓库宝箱解锁信息
    /// </summary>
    [pbr::OriginalName("WareHouseBoxUnlockInfo")] WareHouseBoxUnlockInfo = 54,
    /// <summary>
    /// 仓库宝箱加速
    /// </summary>
    [pbr::OriginalName("WareHouseBoxSpeed")] WareHouseBoxSpeed = 55,
    /// <summary>
    /// 仓库道具使用
    /// </summary>
    [pbr::OriginalName("UseWarehouseGoods")] UseWarehouseGoods = 56,
    /// <summary>
    /// 庄园日志获取
    /// </summary>
    [pbr::OriginalName("GetManorLogs")] GetManorLogs = 57,
    /// <summary>
    /// 购买大厅角色
    /// </summary>
    [pbr::OriginalName("PurchaseRole")] PurchaseRole = 58,
    /// <summary>
    /// 切换大厅角色
    /// </summary>
    [pbr::OriginalName("SwitchoverRole")] SwitchoverRole = 59,
    /// <summary>
    /// 切换服装
    /// </summary>
    [pbr::OriginalName("SwitchoverCostume")] SwitchoverCostume = 60,
    /// <summary>
    /// 获取自己庄园地鼠奖励
    /// </summary>
    [pbr::OriginalName("OneselfMarmot")] OneselfMarmot = 61,
    /// <summary>
    /// 好友庄园地鼠奖励
    /// </summary>
    [pbr::OriginalName("FriendMarmot")] FriendMarmot = 62,
    /// <summary>
    /// 观看番外广告
    /// </summary>
    [pbr::OriginalName("AdvExtraStory")] AdvExtraStory = 63,
    /// <summary>
    /// 世界聊天
    /// </summary>
    [pbr::OriginalName("WorldChat")] WorldChat = 64,
    /// <summary>
    /// 私聊
    /// </summary>
    [pbr::OriginalName("PrivateChat")] PrivateChat = 65,
    /// <summary>
    /// 进入(切换)晚会房间
    /// </summary>
    [pbr::OriginalName("EntranceRoom")] EntranceRoom = 66,
    /// <summary>
    /// 竞猜
    /// </summary>
    [pbr::OriginalName("Guessing")] Guessing = 67,
    /// <summary>
    /// 频道聊天
    /// </summary>
    [pbr::OriginalName("ChannelChat")] ChannelChat = 68,
    /// <summary>
    /// 获取晚会房间列表
    /// </summary>
    [pbr::OriginalName("RoomList")] RoomList = 69,
    /// <summary>
    /// 登录领取好感值
    /// </summary>
    [pbr::OriginalName("LoginGetFavorable")] LoginGetFavorable = 70,
    /// <summary>
    /// 赠送npc礼物
    /// </summary>
    [pbr::OriginalName("SendNPCGift")] SendNpcgift = 71,
    /// <summary>
    /// 章节选项增加好感度
    /// </summary>
    [pbr::OriginalName("SectionAddFavorable")] SectionAddFavorable = 72,
    /// <summary>
    /// 获取好感信息
    /// </summary>
    [pbr::OriginalName("GetFavorableInfo")] GetFavorableInfo = 74,
    /// <summary>
    /// 房间玩家位置移动
    /// </summary>
    [pbr::OriginalName("MoveLocation")] MoveLocation = 75,
    /// <summary>
    /// 退出房间
    /// </summary>
    [pbr::OriginalName("DepartureRoom")] DepartureRoom = 76,
    /// <summary>
    /// 晚会动作
    /// </summary>
    [pbr::OriginalName("Motion")] Motion = 78,
    /// <summary>
    /// 获取庄园地鼠奖励信息
    /// </summary>
    [pbr::OriginalName("GetMarmotAwardInfo")] GetMarmotAwardInfo = 79,
    /// <summary>
    /// 邮件状态更新
    /// </summary>
    [pbr::OriginalName("ChangeMailState")] ChangeMailState = 80,
    /// <summary>
    /// 购物车功能
    /// </summary>
    [pbr::OriginalName("ShoppingTrolley")] ShoppingTrolley = 81,
    /// <summary>
    /// 心跳
    /// </summary>
    [pbr::OriginalName("HeartBeat")] HeartBeat = 82,
    /// <summary>
    /// 累积签到
    /// </summary>
    [pbr::OriginalName("AccumulateSignIn")] AccumulateSignIn = 83,
    /// <summary>
    /// 保存引导
    /// </summary>
    [pbr::OriginalName("SaveGuidance")] SaveGuidance = 84,
    /// <summary>
    /// 好友庄园信息引导
    /// </summary>
    [pbr::OriginalName("ManorGuidance")] ManorGuidance = 87,
    /// <summary>
    /// 好友庄园偷取引导
    /// </summary>
    [pbr::OriginalName("StealManorGuidance")] StealManorGuidance = 88,
    /// <summary>
    /// 获取任务信息
    /// </summary>
    [pbr::OriginalName("GetTaskInfo")] GetTaskInfo = 91,
    /// <summary>
    /// 领取任务奖励
    /// </summary>
    [pbr::OriginalName("GetTaskAward")] GetTaskAward = 92,
    /// <summary>
    /// 注销账号
    /// </summary>
    [pbr::OriginalName("LogoutAccount")] LogoutAccount = 93,
    /// <summary>
    /// cdk兑换
    /// </summary>
    [pbr::OriginalName("CdkConversion")] CdkConversion = 94,
    /// <summary>
    /// 获取订单信息
    /// </summary>
    [pbr::OriginalName("GetDealInfo")] GetDealInfo = 95,
    /// <summary>
    /// 提交订单
    /// </summary>
    [pbr::OriginalName("SubmitDeal")] SubmitDeal = 96,
    /// <summary>
    /// 刷新订单 
    /// </summary>
    [pbr::OriginalName("RefreshDeal")] RefreshDeal = 97,
    /// <summary>
    /// 订单广告跳过
    /// </summary>
    [pbr::OriginalName("AdvSkipDeal")] AdvSkipDeal = 98,
    /// <summary>
    /// 请求进入章节或者番外
    /// </summary>
    [pbr::OriginalName("EntranceSection")] EntranceSection = 99,
    /// <summary>
    /// 庄园作物是否成熟
    /// </summary>
    [pbr::OriginalName("CropMature")] CropMature = 100,
    /// <summary>
    /// 庄园装饰物旋转
    /// </summary>
    [pbr::OriginalName("ManorDecorateRotate")] ManorDecorateRotate = 101,
    /// <summary>
    /// 好友点赞
    /// </summary>
    [pbr::OriginalName("FriendLike")] FriendLike = 102,
    /// <summary>
    /// 好友服饰
    /// </summary>
    [pbr::OriginalName("FriendCostume")] FriendCostume = 103,
    /// <summary>
    /// 一键浇水
    /// </summary>
    [pbr::OriginalName("OnceWatering")] OnceWatering = 104,
    /// <summary>
    /// 装饰物升级
    /// </summary>
    [pbr::OriginalName("DecorateUp")] DecorateUp = 105,
    /// <summary>
    /// 50000以后的操作码都为后端向前端推送
    /// 测试推送消息
    /// </summary>
    [pbr::OriginalName("Test_Data")] TestData = 50000,
    /// <summary>
    /// 账号重复登录
    /// </summary>
    [pbr::OriginalName("RepetitionRegister")] RepetitionRegister = 50001,
    /// <summary>
    /// 申请添加好友
    /// </summary>
    [pbr::OriginalName("ApplyAddFriend")] ApplyAddFriend = 50002,
    /// <summary>
    /// 同意添加好友
    /// </summary>
    [pbr::OriginalName("AcceptAddFriend")] AcceptAddFriend = 50003,
    /// <summary>
    /// 拒绝添加好友
    /// </summary>
    [pbr::OriginalName("RepulseAddFriend")] RepulseAddFriend = 50004,
    /// <summary>
    /// 删除好友
    /// </summary>
    [pbr::OriginalName("DeleteFriend")] DeleteFriend = 50005,
    /// <summary>
    /// 邮件推送
    /// </summary>
    [pbr::OriginalName("MailPush")] MailPush = 50006,
    /// <summary>
    /// 更新好友庄园农作物成熟状态
    /// </summary>
    [pbr::OriginalName("ManorFriend")] ManorFriend = 50007,
    /// <summary>
    /// 公告推送
    /// </summary>
    [pbr::OriginalName("PushNoteMess")] PushNoteMess = 50009,
    /// <summary>
    /// 话筒推送
    /// </summary>
    [pbr::OriginalName("PushVoiceMess")] PushVoiceMess = 50010,
    /// <summary>
    /// 世界聊天推送
    /// </summary>
    [pbr::OriginalName("PushWorldChat")] PushWorldChat = 50011,
    /// <summary>
    /// 私聊
    /// </summary>
    [pbr::OriginalName("PushPrivateChat")] PushPrivateChat = 50012,
    /// <summary>
    /// 频道聊天
    /// </summary>
    [pbr::OriginalName("PushChannelChat")] PushChannelChat = 50013,
    /// <summary>
    /// 进入房间玩家信息
    /// </summary>
    [pbr::OriginalName("PushEntranceRoomInfo")] PushEntranceRoomInfo = 50014,
    /// <summary>
    /// 房间位置移动玩家信息
    /// </summary>
    [pbr::OriginalName("PushMoveLocation")] PushMoveLocation = 50015,
    /// <summary>
    /// 推送竞猜信息
    /// </summary>
    [pbr::OriginalName("PushGuessing")] PushGuessing = 50016,
    /// <summary>
    /// 推送晚会动作
    /// </summary>
    [pbr::OriginalName("PushMotion")] PushMotion = 50017,
    /// <summary>
    /// 退出房间
    /// </summary>
    [pbr::OriginalName("PushDepartureRoom")] PushDepartureRoom = 50018,
    /// <summary>
    /// 活动结束
    /// </summary>
    [pbr::OriginalName("PushActivityFinish")] PushActivityFinish = 50019,
    /// <summary>
    /// 账号重复登录
    /// </summary>
    [pbr::OriginalName("PushRepetitionRegister")] PushRepetitionRegister = 50020,
    /// <summary>
    /// 服务器强制更新
    /// </summary>
    [pbr::OriginalName("PushCoerceRenewal")] PushCoerceRenewal = 60000,
  }

  /// <summary>
  /// 服务器状态
  /// </summary>
  public enum ServerStatus {
    /// <summary>
    /// 未知
    /// </summary>
    [pbr::OriginalName("ServerStatusNone")] None = 0,
    /// <summary>
    /// 正常
    /// </summary>
    [pbr::OriginalName("Normal")] Normal = 1,
    /// <summary>
    /// 维护
    /// </summary>
    [pbr::OriginalName("Maintain")] Maintain = 2,
  }

  /// <summary>
  /// 登录平台
  /// </summary>
  public enum RegisterPlatform {
    /// <summary>
    /// 未知
    /// </summary>
    [pbr::OriginalName("RegisterPlatformNone")] None = 0,
    /// <summary>
    /// QQ
    /// </summary>
    [pbr::OriginalName("Qq")] Qq = 1,
    /// <summary>
    /// 微信
    /// </summary>
    [pbr::OriginalName("WeChat")] WeChat = 2,
  }

  /// <summary>
  /// 庄园成熟
  /// </summary>
  public enum manorMature {
    /// <summary>
    /// 未知
    /// </summary>
    [pbr::OriginalName("manorMatureNone")] None = 0,
    /// <summary>
    /// 成熟
    /// </summary>
    [pbr::OriginalName("mature")] Mature = 1,
    /// <summary>
    /// 未成熟
    /// </summary>
    [pbr::OriginalName("immature")] Immature = 2,
  }

  /// <summary>
  /// webscoekt错误码
  /// </summary>
  public enum WebscoektError {
    [pbr::OriginalName("WebscoektErrorNone")] None = 0,
    /// <summary>
    /// 正常关闭
    /// </summary>
    [pbr::OriginalName("CLOSENORMAL")] Closenormal = 1000,
    /// <summary>
    /// 终端离开可能因为服务端错误
    /// </summary>
    [pbr::OriginalName("CLOSEGOINGAWAY")] Closegoingaway = 1001,
    /// <summary>
    /// 由于协议错误而中断连接。
    /// </summary>
    [pbr::OriginalName("CLOSEPROTOCOLERROR")] Closeprotocolerror = 1002,
    /// <summary>
    /// 由于接收到不允许的数据类型而断开连接
    /// </summary>
    [pbr::OriginalName("CLOSEUNSUPPORTED")] Closeunsupported = 1003,
    /// <summary>
    /// 表示没有收到预期的状态码
    /// </summary>
    [pbr::OriginalName("CLOSENOSTATUS")] Closenostatus = 1005,
    /// <summary>
    /// 用于期望收到状态码时连接非正常关闭
    /// </summary>
    [pbr::OriginalName("CLOSEABNORMAL")] Closeabnormal = 1006,
    /// <summary>
    /// 由于收到了格式不符的数据而断开连接 
    /// </summary>
    [pbr::OriginalName("UnsupportedData")] UnsupportedData = 1007,
    /// <summary>
    /// 由于收到不符合约定的数据而断开连接
    /// </summary>
    [pbr::OriginalName("PolicyViolation")] PolicyViolation = 1008,
    /// <summary>
    /// 由于收到过大的数据帧而断开连接
    /// </summary>
    [pbr::OriginalName("CLOSETOOLARGE")] Closetoolarge = 1009,
    /// <summary>
    /// 客户端期望服务器商定一个或多个拓展, 但服务器没有处理, 因此客户端断开连接
    /// </summary>
    [pbr::OriginalName("MissingExtension")] MissingExtension = 1010,
    /// <summary>
    /// 客户端由于遇到没有预料的情况阻止其完成请求, 因此服务端断开连接
    /// </summary>
    [pbr::OriginalName("InternalError")] InternalError = 1011,
    /// <summary>
    /// 服务器由于重启而断开连接
    /// </summary>
    [pbr::OriginalName("ServiceRestart")] ServiceRestart = 1012,
    /// <summary>
    /// 服务器由于临时原因断开连接, 如服务器过载因此断开一部分客户端连接
    /// </summary>
    [pbr::OriginalName("TryAgainLater")] TryAgainLater = 1013,
    /// <summary>
    /// 表示连接由于无法完成 TLS 握手而关闭 
    /// </summary>
    [pbr::OriginalName("TLSHandshake")] Tlshandshake = 1015,
  }

  /// <summary>
  /// 服务器类型
  /// </summary>
  public enum ServerType {
    [pbr::OriginalName("ServerTypeNone")] None = 0,
    /// <summary>
    /// 连接服务器
    /// </summary>
    [pbr::OriginalName("LinkServer")] LinkServer = 1,
    /// <summary>
    /// 逻辑服务器
    /// </summary>
    [pbr::OriginalName("LogicServer")] LogicServer = 2,
    /// <summary>
    /// 聊天服务器
    /// </summary>
    [pbr::OriginalName("ChatServer")] ChatServer = 3,
    /// <summary>
    /// 晚会服务器
    /// </summary>
    [pbr::OriginalName("SoireeServer")] SoireeServer = 4,
  }

  /// <summary>
  /// 庄园场景类型
  /// </summary>
  public enum ManorScene {
    /// <summary>
    /// 没有
    /// </summary>
    [pbr::OriginalName("ManorSceneNone")] None = 0,
    /// <summary>
    /// 地块
    /// </summary>
    [pbr::OriginalName("Tile")] Tile = 1,
    /// <summary>
    /// 狗屋
    /// </summary>
    [pbr::OriginalName("DogHouse")] DogHouse = 2,
    /// <summary>
    /// 宝箱，礼盒
    /// </summary>
    [pbr::OriginalName("GiftBox")] GiftBox = 3,
    /// <summary>
    /// 装饰物
    /// </summary>
    [pbr::OriginalName("Decorate")] Decorate = 4,
    /// <summary>
    /// Npc
    /// </summary>
    [pbr::OriginalName("Npc")] Npc = 5,
  }

  /// <summary>
  /// 购买消费类型
  /// </summary>
  public enum ConsumptionType {
    [pbr::OriginalName("ConsumptionTypeNone")] None = 0,
    /// <summary>
    /// 金币
    /// </summary>
    [pbr::OriginalName("Gold")] Gold = 1,
    /// <summary>
    /// 钻石
    /// </summary>
    [pbr::OriginalName("Diamond")] Diamond = 2,
  }

  /// <summary>
  /// 宝箱解锁类型
  /// </summary>
  public enum UnlockTreasureChest {
    [pbr::OriginalName("UnlockTreasureChestNone")] None = 0,
    /// <summary>
    /// 钥匙
    /// </summary>
    [pbr::OriginalName("Key")] Key = 1,
    /// <summary>
    /// 倒计时
    /// </summary>
    [pbr::OriginalName("CountDown")] CountDown = 2,
  }

  /// <summary>
  /// 作物阶段
  /// </summary>
  public enum PeriodGrow {
    /// <summary>
    /// 种子
    /// </summary>
    [pbr::OriginalName("Seed")] Seed = 0,
    /// <summary>
    /// 发芽
    /// </summary>
    [pbr::OriginalName("Germinate")] Germinate = 1,
    /// <summary>
    /// 成长
    /// </summary>
    [pbr::OriginalName("GrowUp")] GrowUp = 2,
    /// <summary>
    /// 成熟期
    /// </summary>
    [pbr::OriginalName("Ripe")] Ripe = 3,
  }

  /// <summary>
  /// 区域状态
  /// </summary>
  public enum AreaState {
    /// <summary>
    /// 未解锁
    /// </summary>
    [pbr::OriginalName("NoUnlock")] NoUnlock = 0,
    /// <summary>
    /// 对话状态
    /// </summary>
    [pbr::OriginalName("Conversation")] Conversation = 1,
    /// <summary>
    /// 支付阶段
    /// </summary>
    [pbr::OriginalName("Pay")] Pay = 2,
    /// <summary>
    /// 施工阶段
    /// </summary>
    [pbr::OriginalName("RoadWork")] RoadWork = 3,
    /// <summary>
    /// 工棚状态 
    /// </summary>
    [pbr::OriginalName("WorkShed")] WorkShed = 4,
    /// <summary>
    /// 移除工棚状态
    /// </summary>
    [pbr::OriginalName("RemoveWorkShed")] RemoveWorkShed = 5,
  }

  /// <summary>
  /// 是否促销
  /// </summary>
  public enum IsPromotion {
    [pbr::OriginalName("IsPromotionNone")] None = 0,
    /// <summary>
    /// 原价
    /// </summary>
    [pbr::OriginalName("Original")] Original = 1,
    /// <summary>
    /// 促销
    /// </summary>
    [pbr::OriginalName("Promotion")] Promotion = 2,
  }

  /// <summary>
  /// 道具商店购买方式
  /// </summary>
  public enum GoodsBuyWay {
    [pbr::OriginalName("GoodsBuyWayNone")] None = 0,
    /// <summary>
    /// 第一种方式
    /// </summary>
    [pbr::OriginalName("FirstWay")] FirstWay = 1,
    /// <summary>
    /// 第二种方式
    /// </summary>
    [pbr::OriginalName("SecondWay")] SecondWay = 2,
  }

  /// <summary>
  /// 工棚加速方式
  /// </summary>
  public enum WorkShedSpeedUpWay {
    [pbr::OriginalName("WorkShedSpeedUpWayNone")] None = 0,
    /// <summary>
    /// 广告加速
    /// </summary>
    [pbr::OriginalName("AdvertisingWay")] AdvertisingWay = 1,
    /// <summary>
    /// 钻石方式
    /// </summary>
    [pbr::OriginalName("DiamondWay")] DiamondWay = 2,
  }

  /// <summary>
  /// 不占用仓库格子道具ID列表
  /// </summary>
  public enum WarehouseShieldIDList {
    [pbr::OriginalName("WarehouseShieldIDListNone")] None = 0,
    /// <summary>
    /// 钻石
    /// </summary>
    [pbr::OriginalName("JewelID")] JewelId = 1000001,
    /// <summary>
    /// 金币
    /// </summary>
    [pbr::OriginalName("GoldID")] GoldId = 1000002,
    /// <summary>
    /// 积分
    /// </summary>
    [pbr::OriginalName("IntegralID")] IntegralId = 1000003,
    /// <summary>
    /// 体力
    /// </summary>
    [pbr::OriginalName("PowerID")] PowerId = 2000001,
    /// <summary>
    /// 好感值
    /// </summary>
    [pbr::OriginalName("FavorableID")] FavorableId = 2000012,
  }

  /// <summary>
  /// 道具使用类型
  /// </summary>
  public enum GoodsUseType {
    [pbr::OriginalName("GoodsUseTypeNone")] None = 0,
    /// <summary>
    /// 扩展包类型
    /// </summary>
    [pbr::OriginalName("ExtendBag")] ExtendBag = 5,
    /// <summary>
    /// 仓库礼盒类型
    /// </summary>
    [pbr::OriginalName("GitfBox")] GitfBox = 7,
    /// <summary>
    /// 话筒类型
    /// </summary>
    [pbr::OriginalName("VoiceType")] VoiceType = 8,
  }

  /// <summary>
  /// 庄园偷取类型
  /// </summary>
  public enum ManorStealType {
    [pbr::OriginalName("ManorStealTypeNone")] None = 0,
    /// <summary>
    /// 农作物
    /// </summary>
    [pbr::OriginalName("CropType")] CropType = 1,
    /// <summary>
    /// 地鼠
    /// </summary>
    [pbr::OriginalName("DiglettType")] DiglettType = 2,
  }

  /// <summary>
  /// 竞技编号
  /// </summary>
  public enum GuessingNumber {
    [pbr::OriginalName("GuessingNone")] GuessingNone = 0,
    [pbr::OriginalName("GuessingFirst")] GuessingFirst = 1,
    [pbr::OriginalName("GuessingSecond")] GuessingSecond = 2,
    [pbr::OriginalName("GuessingThird")] GuessingThird = 3,
  }

  /// <summary>
  /// 竞技状态
  /// </summary>
  public enum GuessingStatus {
    [pbr::OriginalName("StatusNone")] StatusNone = 0,
    /// <summary>
    /// 加速
    /// </summary>
    [pbr::OriginalName("StatusSpeed")] StatusSpeed = 10001,
    /// <summary>
    /// 减速
    /// </summary>
    [pbr::OriginalName("StatusSlowDown")] StatusSlowDown = 10002,
    /// <summary>
    /// 无敌
    /// </summary>
    [pbr::OriginalName("StatusInvincible")] StatusInvincible = 10003,
    /// <summary>
    /// 禁锢
    /// </summary>
    [pbr::OriginalName("StatusImprisoned")] StatusImprisoned = 10004,
    /// <summary>
    /// 活动结束
    /// </summary>
    [pbr::OriginalName("StatusFinish")] StatusFinish = 10005,
  }

  /// <summary>
  /// 公告道具来源
  /// </summary>
  public enum PushNoticeGoodsSource {
    [pbr::OriginalName("PushNoticeGoodsSourceNone")] None = 0,
    /// <summary>
    /// 大富翁
    /// </summary>
    [pbr::OriginalName("ZillionairePushType")] ZillionairePushType = 1,
    /// <summary>
    /// 庄园地鼠
    /// </summary>
    [pbr::OriginalName("ManorDiglettType")] ManorDiglettType = 2,
    /// <summary>
    /// 宝箱
    /// </summary>
    [pbr::OriginalName("TreasureBoxType")] TreasureBoxType = 3,
  }

  /// <summary>
  /// 公告源
  /// </summary>
  public enum PushNoticeSource {
    [pbr::OriginalName("PushNoticeSourceNone")] None = 0,
    /// <summary>
    /// 系统
    /// </summary>
    [pbr::OriginalName("SystemType")] SystemType = 1,
    /// <summary>
    /// 玩家
    /// </summary>
    [pbr::OriginalName("PlayerType")] PlayerType = 2,
  }

  /// <summary>
  /// 好感值领取状态
  /// </summary>
  public enum GetFavorableState {
    [pbr::OriginalName("GetFavorableStateNone")] None = 0,
    /// <summary>
    /// 未领
    /// </summary>
    [pbr::OriginalName("NeverGetType")] NeverGetType = 1,
    /// <summary>
    /// 已领
    /// </summary>
    [pbr::OriginalName("AlreadyGetType")] AlreadyGetType = 2,
  }

  /// <summary>
  /// 邮件状态
  /// </summary>
  public enum MailState {
    [pbr::OriginalName("MailStateNone")] None = 0,
    /// <summary>
    /// 未读
    /// </summary>
    [pbr::OriginalName("UnReadState")] UnReadState = 1,
    /// <summary>
    /// 已读已领
    /// </summary>
    [pbr::OriginalName("ReadAlreadyState")] ReadAlreadyState = 2,
    /// <summary>
    /// 已读未领
    /// </summary>
    [pbr::OriginalName("ReadUnAlreadyState")] ReadUnAlreadyState = 3,
    /// <summary>
    /// 删除
    /// </summary>
    [pbr::OriginalName("DeleteState")] DeleteState = 4,
  }

  /// <summary>
  /// 商店道具特殊类型
  /// </summary>
  public enum ShopItemType {
    [pbr::OriginalName("ShopItemTypeNone")] None = 0,
    /// <summary>
    /// 角色
    /// </summary>
    [pbr::OriginalName("Character")] Character = 5,
    /// <summary>
    /// 商店服装
    /// </summary>
    [pbr::OriginalName("StoreClothing")] StoreClothing = 6,
    /// <summary>
    /// 积分商店服装
    /// </summary>
    [pbr::OriginalName("PointsStoreClothing")] PointsStoreClothing = 7,
    /// <summary>
    /// 头像
    /// </summary>
    [pbr::OriginalName("HeadImage")] HeadImage = 8,
  }

  /// <summary>
  /// 晚会活动比赛状态
  /// </summary>
  public enum SoireeGameStates {
    [pbr::OriginalName("SoireeGameStatesNone")] None = 0,
    /// <summary>
    /// 下注期
    /// </summary>
    [pbr::OriginalName("BetStates")] BetStates = 1,
    /// <summary>
    /// 比赛期
    /// </summary>
    [pbr::OriginalName("GameState")] GameState = 2,
  }

  /// <summary>
  /// 骰子类型
  /// </summary>
  public enum DiceType {
    [pbr::OriginalName("DiceTypeNone")] None = 0,
    /// <summary>
    /// 低位随机(1~3)
    /// </summary>
    [pbr::OriginalName("LowDice")] LowDice = 1,
    /// <summary>
    /// 高位随机(4~6)
    /// </summary>
    [pbr::OriginalName("HighDice")] HighDice = 2,
    /// <summary>
    /// 纯随机(1~6)
    /// </summary>
    [pbr::OriginalName("PureDice")] PureDice = 3,
  }

  /// <summary>
  /// 抽奖类型
  /// </summary>
  public enum LuckyTyep {
    [pbr::OriginalName("LuckyNone")] LuckyNone = 0,
    /// <summary>
    /// 种子抽奖
    /// </summary>
    [pbr::OriginalName("LuckySeed")] LuckySeed = 1,
    /// <summary>
    /// 道具抽奖
    /// </summary>
    [pbr::OriginalName("LuckyProp")] LuckyProp = 2,
  }

  /// <summary>
  /// 任务类型
  /// </summary>
  public enum TaskType {
    [pbr::OriginalName("TaskTypeNone")] None = 0,
    /// <summary>
    /// 新手引导任务
    /// </summary>
    [pbr::OriginalName("GuidanceTaskType")] GuidanceTaskType = 1,
    /// <summary>
    /// 日常任务
    /// </summary>
    [pbr::OriginalName("DailyTaskType")] DailyTaskType = 2,
  }

  /// <summary>
  /// 每日任务
  /// </summary>
  public enum TaskID {
    [pbr::OriginalName("TaskIDNone")] None = 0,
    /// <summary>
    /// 登录
    /// </summary>
    [pbr::OriginalName("LoginTask")] LoginTask = 20001,
    /// <summary>
    /// 签到
    /// </summary>
    [pbr::OriginalName("SignInTask")] SignInTask = 20002,
    /// <summary>
    /// 每日领取心动值
    /// </summary>
    [pbr::OriginalName("DailyGetImpulseTask")] DailyGetImpulseTask = 20003,
    /// <summary>
    /// 进入庄园
    /// </summary>
    [pbr::OriginalName("InManorTask")] InManorTask = 20004,
    /// <summary>
    /// 播种
    /// </summary>
    [pbr::OriginalName("PlantTask")] PlantTask = 20005,
    /// <summary>
    /// 收获
    /// </summary>
    [pbr::OriginalName("HarvestTask")] HarvestTask = 20006,
    /// <summary>
    /// 施肥
    /// </summary>
    [pbr::OriginalName("FertilizerTask")] FertilizerTask = 20007,
    /// <summary>
    /// 装扮庄园
    /// </summary>
    [pbr::OriginalName("DressManorTask")] DressManorTask = 20008,
    /// <summary>
    /// 出售果实
    /// </summary>
    [pbr::OriginalName("SellFruitTask")] SellFruitTask = 20009,
    /// <summary>
    /// 开启普通宝箱
    /// </summary>
    [pbr::OriginalName("OpenOrdinaryTask")] OpenOrdinaryTask = 20010,
    /// <summary>
    /// 开启中级宝箱
    /// </summary>
    [pbr::OriginalName("OpenIntermediateTask")] OpenIntermediateTask = 20011,
    /// <summary>
    /// 开启特制宝箱
    /// </summary>
    [pbr::OriginalName("OpenSeniorTask")] OpenSeniorTask = 20012,
    /// <summary>
    /// 自己庄园地鼠
    /// </summary>
    [pbr::OriginalName("ManorDiglettTask")] ManorDiglettTask = 20013,
    /// <summary>
    /// 好友庄园地鼠
    /// </summary>
    [pbr::OriginalName("FriendManorDiglettTask")] FriendManorDiglettTask = 20014,
    /// <summary>
    /// 消耗体力
    /// </summary>
    [pbr::OriginalName("UsePowerTask")] UsePowerTask = 20015,
    /// <summary>
    /// 夹娃娃
    /// </summary>
    [pbr::OriginalName("CatchDollTask")] CatchDollTask = 20016,
    /// <summary>
    /// 猜豆子
    /// </summary>
    [pbr::OriginalName("GuessBeansTask")] GuessBeansTask = 20017,
    /// <summary>
    /// 观看剧情
    /// </summary>
    [pbr::OriginalName("WatchSectionTask")] WatchSectionTask = 20018,
    /// <summary>
    /// 解锁朋友圈
    /// </summary>
    [pbr::OriginalName("UnLockCircleFriendsTask")] UnLockCircleFriendsTask = 20019,
    /// <summary>
    /// 赠送礼物
    /// </summary>
    [pbr::OriginalName("SendGiftTask")] SendGiftTask = 20020,
    /// <summary>
    /// 完成低级订单
    /// </summary>
    [pbr::OriginalName("FinishLowDeal")] FinishLowDeal = 20021,
    /// <summary>
    /// 完成中级订单
    /// </summary>
    [pbr::OriginalName("FinishMiddleDeal")] FinishMiddleDeal = 20022,
    /// <summary>
    /// 完成高级订单
    /// </summary>
    [pbr::OriginalName("FinishHighDeal")] FinishHighDeal = 20023,
  }

  /// <summary>
  /// 引导任务
  /// </summary>
  public enum GuideTask {
    [pbr::OriginalName("GuideTaskNone")] None = 0,
    /// <summary>
    /// 种植播种
    /// </summary>
    [pbr::OriginalName("GuideSeed")] GuideSeed = 10003,
    /// <summary>
    /// 种植施肥
    /// </summary>
    [pbr::OriginalName("GuideFertilizer")] GuideFertilizer = 10004,
    /// <summary>
    /// 种植收获
    /// </summary>
    [pbr::OriginalName("GuideHarvest")] GuideHarvest = 10005,
    /// <summary>
    /// 售卖作物
    /// </summary>
    [pbr::OriginalName("GuideSellFruit")] GuideSellFruit = 10008,
    /// <summary>
    /// 购买种子
    /// </summary>
    [pbr::OriginalName("GuideBuySeed")] GuideBuySeed = 10011,
    /// <summary>
    /// 偷取果实
    /// </summary>
    [pbr::OriginalName("GuideSteal")] GuideSteal = 10024,
    /// <summary>
    /// 放置装饰
    /// </summary>
    [pbr::OriginalName("GuideDecorate")] GuideDecorate = 11026,
    /// <summary>
    /// 移动装饰物
    /// </summary>
    [pbr::OriginalName("GuideMoveDecorate")] GuideMoveDecorate = 11027,
    /// <summary>
    /// 移动地块
    /// </summary>
    [pbr::OriginalName("GuideMoveSoil")] GuideMoveSoil = 11028,
    /// <summary>
    /// 抓地鼠
    /// </summary>
    [pbr::OriginalName("GuideDiglett")] GuideDiglett = 11029,
    /// <summary>
    /// 投掷全随机骰子
    /// </summary>
    [pbr::OriginalName("GuideRandom")] GuideRandom = 11030,
    /// <summary>
    /// 投掷低位随机骰子
    /// </summary>
    [pbr::OriginalName("GuideLow")] GuideLow = 11031,
    /// <summary>
    /// 投掷高位随机骰子
    /// </summary>
    [pbr::OriginalName("GuideHigh")] GuideHigh = 11032,
    /// <summary>
    /// 观看章节
    /// </summary>
    [pbr::OriginalName("GuideChapter")] GuideChapter = 11033,
    /// <summary>
    /// 成功解锁区域
    /// </summary>
    [pbr::OriginalName("GuideArea")] GuideArea = 11034,
    /// <summary>
    /// 完成订单
    /// </summary>
    [pbr::OriginalName("FinishDeal")] FinishDeal = 11035,
  }

  /// <summary>
  /// 仓库宝箱ID
  /// </summary>
  public enum WarehouseBoxID {
    [pbr::OriginalName("WarehouseBoxIDNone")] None = 0,
    /// <summary>
    /// 普通宝箱
    /// </summary>
    [pbr::OriginalName("OrdinaryBox")] OrdinaryBox = 3000001,
    /// <summary>
    /// 中级宝箱
    /// </summary>
    [pbr::OriginalName("IntermediateBox")] IntermediateBox = 3000002,
    /// <summary>
    /// 特级宝箱
    /// </summary>
    [pbr::OriginalName("SeniorBox")] SeniorBox = 3000003,
  }

  /// <summary>
  /// 功能开发
  /// </summary>
  public enum OpenFunction {
    [pbr::OriginalName("OpenNone")] OpenNone = 0,
    /// <summary>
    /// 庄园种植、施肥、收获
    /// </summary>
    [pbr::OriginalName("OpenManor")] OpenManor = 10001,
    /// <summary>
    /// 仓库
    /// </summary>
    [pbr::OriginalName("OpenWarehouse")] OpenWarehouse = 10002,
    /// <summary>
    /// 新手培训任务
    /// </summary>
    [pbr::OriginalName("OpenGuidance")] OpenGuidance = 10003,
    /// <summary>
    /// 邮件
    /// </summary>
    [pbr::OriginalName("OpenMail")] OpenMail = 10004,
    /// <summary>
    /// 个人信息
    /// </summary>
    [pbr::OriginalName("OpenUserInfo")] OpenUserInfo = 10005,
    /// <summary>
    /// 大厅好友
    /// </summary>
    [pbr::OriginalName("OpenLobbyFriend")] OpenLobbyFriend = 10006,
    /// <summary>
    /// 章节
    /// </summary>
    [pbr::OriginalName("OpenChapter")] OpenChapter = 10007,
    /// <summary>
    /// 商店
    /// </summary>
    [pbr::OriginalName("OpenStore")] OpenStore = 10008,
    /// <summary>
    /// 移动、缩放庄园
    /// </summary>
    [pbr::OriginalName("OpenMoveManor")] OpenMoveManor = 10009,
    /// <summary>
    /// 抓地鼠
    /// </summary>
    [pbr::OriginalName("OpenDiglett")] OpenDiglett = 10010,
    /// <summary>
    /// 大富翁
    /// </summary>
    [pbr::OriginalName("OpenRichMan")] OpenRichMan = 10011,
    /// <summary>
    /// 装扮功能
    /// </summary>
    [pbr::OriginalName("OpenDecorate")] OpenDecorate = 10012,
    /// <summary>
    /// 庄园好友
    /// </summary>
    [pbr::OriginalName("OpenManorFriend")] OpenManorFriend = 10013,
    /// <summary>
    /// 每日任务
    /// </summary>
    [pbr::OriginalName("OpenTask")] OpenTask = 10014,
    /// <summary>
    /// 心动时刻
    /// </summary>
    [pbr::OriginalName("OpenImpulse")] OpenImpulse = 10015,
    /// <summary>
    /// 活动
    /// </summary>
    [pbr::OriginalName("OpenActivity")] OpenActivity = 10016,
    /// <summary>
    /// 晚会
    /// </summary>
    [pbr::OriginalName("OpenEvening")] OpenEvening = 10017,
    /// <summary>
    /// 庄园日志
    /// </summary>
    [pbr::OriginalName("OpenManorLog")] OpenManorLog = 10018,
    /// <summary>
    /// 一件收获
    /// </summary>
    [pbr::OriginalName("OpenOneKeyHarvest")] OpenOneKeyHarvest = 10020,
    /// <summary>
    /// 钻石购买
    /// </summary>
    [pbr::OriginalName("OpenBuyJewel")] OpenBuyJewel = 20001,
  }

  /// <summary>
  /// 邮件事件ID
  /// </summary>
  public enum MailConfigID {
    [pbr::OriginalName("MailConfigIDNone")] None = 0,
    /// <summary>
    /// 大富翁
    /// </summary>
    [pbr::OriginalName("RichManMail")] RichManMail = 1001,
    /// <summary>
    /// 庄园地鼠
    /// </summary>
    [pbr::OriginalName("ManorMail")] ManorMail = 1002,
    /// <summary>
    /// 礼盒
    /// </summary>
    [pbr::OriginalName("GiftMail")] GiftMail = 1003,
    /// <summary>
    /// 仓库宝箱
    /// </summary>
    [pbr::OriginalName("WareHouseBox")] WareHouseBox = 1004,
  }

  /// <summary>
  /// 普通邮件国际化ID
  /// </summary>
  public enum MailLocalizeID {
    [pbr::OriginalName("MailLocalizeIDNone")] None = 0,
    /// <summary>
    /// 仓库已满标题
    /// </summary>
    [pbr::OriginalName("WarehouseFullMailTitle")] WarehouseFullMailTitle = 310000001,
    /// <summary>
    /// 仓库已满副标题
    /// </summary>
    [pbr::OriginalName("WarehouseFullMailSubhead")] WarehouseFullMailSubhead = 320000002,
    /// <summary>
    /// 仓库已满正文
    /// </summary>
    [pbr::OriginalName("WarehouseFullMailMessage")] WarehouseFullMailMessage = 330000003,
  }

  /// <summary>
  /// 订单类型
  /// </summary>
  public enum DealType {
    [pbr::OriginalName("DealTypeNone")] None = 0,
    /// <summary>
    /// 低级订单
    /// </summary>
    [pbr::OriginalName("LowLevel")] LowLevel = 1,
    /// <summary>
    /// 中级
    /// </summary>
    [pbr::OriginalName("MiddleLevel")] MiddleLevel = 2,
    /// <summary>
    /// 高级
    /// </summary>
    [pbr::OriginalName("HighLevel")] HighLevel = 3,
  }

  /// <summary>
  /// 任务订单奖励类型
  /// </summary>
  public enum DealAwardType {
    [pbr::OriginalName("DealAwardTypeNone")] None = 0,
    /// <summary>
    /// 钻石
    /// </summary>
    [pbr::OriginalName("DealAwardJewelID")] DealAwardJewelId = 1000001,
    /// <summary>
    /// 金币
    /// </summary>
    [pbr::OriginalName("DealAwardGoldID")] DealAwardGoldId = 1000002,
    /// <summary>
    /// 水滴营养液
    /// </summary>
    [pbr::OriginalName("DealAwardWater")] DealAwardWater = 2000005,
    /// <summary>
    /// 经验
    /// </summary>
    [pbr::OriginalName("DealAwardExp")] DealAwardExp = 2000004,
  }

  #endregion

}

#endregion Designer generated code
