// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Guidance.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Game.Protocal {

  /// <summary>Holder for reflection information generated from Guidance.proto</summary>
  public static partial class GuidanceReflection {

    #region Descriptor
    /// <summary>File descriptor for Guidance.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GuidanceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5HdWlkYW5jZS5wcm90bxINR2FtZS5Qcm90b2NhbBoLTWFub3IucHJvdG8i",
            "NwoOQ1NTYXZlR3VpZGFuY2USEAoIR3VpZGFuY2UYASABKAUSEwoLR3VpZGFu",
            "Y2VOdW0YAiABKAUifQoPU0NNYW5vckd1aWRhbmNlEi8KCU1hbm9ySW5mbxgB",
            "IAMoCzIcLkdhbWUuUHJvdG9jYWwuU0NNYW5vclN0cnVjdBI5Cg5VbmxvY2tB",
            "cmVhSW5mbxgCIAMoCzIhLkdhbWUuUHJvdG9jYWwuU0NVbmxvY2tBcmVhU3Ry",
            "dWN0IkkKFFNDU3RlYWxNYW5vckd1aWRhbmNlEjEKC1N0ZWFsUmVzdWx0GAEg",
            "AygLMhwuR2FtZS5Qcm90b2NhbC5TQ1N0ZWFsUmVzdWx0YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Game.Protocal.ManorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Protocal.CSSaveGuidance), global::Game.Protocal.CSSaveGuidance.Parser, new[]{ "Guidance", "GuidanceNum" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Protocal.SCManorGuidance), global::Game.Protocal.SCManorGuidance.Parser, new[]{ "ManorInfo", "UnlockAreaInfo" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Protocal.SCStealManorGuidance), global::Game.Protocal.SCStealManorGuidance.Parser, new[]{ "StealResult" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 保存引导
  /// </summary>
  public sealed partial class CSSaveGuidance : pb::IMessage<CSSaveGuidance> {
    private static readonly pb::MessageParser<CSSaveGuidance> _parser = new pb::MessageParser<CSSaveGuidance>(() => new CSSaveGuidance());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CSSaveGuidance> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Protocal.GuidanceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSSaveGuidance() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSSaveGuidance(CSSaveGuidance other) : this() {
      guidance_ = other.guidance_;
      guidanceNum_ = other.guidanceNum_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSSaveGuidance Clone() {
      return new CSSaveGuidance(this);
    }

    /// <summary>Field number for the "Guidance" field.</summary>
    public const int GuidanceFieldNumber = 1;
    private int guidance_;
    /// <summary>
    /// 引导id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Guidance {
      get { return guidance_; }
      set {
        guidance_ = value;
      }
    }

    /// <summary>Field number for the "GuidanceNum" field.</summary>
    public const int GuidanceNumFieldNumber = 2;
    private int guidanceNum_;
    /// <summary>
    /// 引导次数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GuidanceNum {
      get { return guidanceNum_; }
      set {
        guidanceNum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CSSaveGuidance);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CSSaveGuidance other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Guidance != other.Guidance) return false;
      if (GuidanceNum != other.GuidanceNum) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Guidance != 0) hash ^= Guidance.GetHashCode();
      if (GuidanceNum != 0) hash ^= GuidanceNum.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Guidance != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Guidance);
      }
      if (GuidanceNum != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GuidanceNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Guidance != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Guidance);
      }
      if (GuidanceNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GuidanceNum);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CSSaveGuidance other) {
      if (other == null) {
        return;
      }
      if (other.Guidance != 0) {
        Guidance = other.Guidance;
      }
      if (other.GuidanceNum != 0) {
        GuidanceNum = other.GuidanceNum;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Guidance = input.ReadInt32();
            break;
          }
          case 16: {
            GuidanceNum = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 返回引导庄园信息
  /// </summary>
  public sealed partial class SCManorGuidance : pb::IMessage<SCManorGuidance> {
    private static readonly pb::MessageParser<SCManorGuidance> _parser = new pb::MessageParser<SCManorGuidance>(() => new SCManorGuidance());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SCManorGuidance> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Protocal.GuidanceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCManorGuidance() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCManorGuidance(SCManorGuidance other) : this() {
      manorInfo_ = other.manorInfo_.Clone();
      unlockAreaInfo_ = other.unlockAreaInfo_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCManorGuidance Clone() {
      return new SCManorGuidance(this);
    }

    /// <summary>Field number for the "ManorInfo" field.</summary>
    public const int ManorInfoFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Game.Protocal.SCManorStruct> _repeated_manorInfo_codec
        = pb::FieldCodec.ForMessage(10, global::Game.Protocal.SCManorStruct.Parser);
    private readonly pbc::RepeatedField<global::Game.Protocal.SCManorStruct> manorInfo_ = new pbc::RepeatedField<global::Game.Protocal.SCManorStruct>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Game.Protocal.SCManorStruct> ManorInfo {
      get { return manorInfo_; }
    }

    /// <summary>Field number for the "UnlockAreaInfo" field.</summary>
    public const int UnlockAreaInfoFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Game.Protocal.SCUnlockAreaStruct> _repeated_unlockAreaInfo_codec
        = pb::FieldCodec.ForMessage(18, global::Game.Protocal.SCUnlockAreaStruct.Parser);
    private readonly pbc::RepeatedField<global::Game.Protocal.SCUnlockAreaStruct> unlockAreaInfo_ = new pbc::RepeatedField<global::Game.Protocal.SCUnlockAreaStruct>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Game.Protocal.SCUnlockAreaStruct> UnlockAreaInfo {
      get { return unlockAreaInfo_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SCManorGuidance);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SCManorGuidance other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!manorInfo_.Equals(other.manorInfo_)) return false;
      if(!unlockAreaInfo_.Equals(other.unlockAreaInfo_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= manorInfo_.GetHashCode();
      hash ^= unlockAreaInfo_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      manorInfo_.WriteTo(output, _repeated_manorInfo_codec);
      unlockAreaInfo_.WriteTo(output, _repeated_unlockAreaInfo_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += manorInfo_.CalculateSize(_repeated_manorInfo_codec);
      size += unlockAreaInfo_.CalculateSize(_repeated_unlockAreaInfo_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SCManorGuidance other) {
      if (other == null) {
        return;
      }
      manorInfo_.Add(other.manorInfo_);
      unlockAreaInfo_.Add(other.unlockAreaInfo_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            manorInfo_.AddEntriesFrom(input, _repeated_manorInfo_codec);
            break;
          }
          case 18: {
            unlockAreaInfo_.AddEntriesFrom(input, _repeated_unlockAreaInfo_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 返回引导偷取
  /// </summary>
  public sealed partial class SCStealManorGuidance : pb::IMessage<SCStealManorGuidance> {
    private static readonly pb::MessageParser<SCStealManorGuidance> _parser = new pb::MessageParser<SCStealManorGuidance>(() => new SCStealManorGuidance());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SCStealManorGuidance> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Protocal.GuidanceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCStealManorGuidance() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCStealManorGuidance(SCStealManorGuidance other) : this() {
      stealResult_ = other.stealResult_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCStealManorGuidance Clone() {
      return new SCStealManorGuidance(this);
    }

    /// <summary>Field number for the "StealResult" field.</summary>
    public const int StealResultFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Game.Protocal.SCStealResult> _repeated_stealResult_codec
        = pb::FieldCodec.ForMessage(10, global::Game.Protocal.SCStealResult.Parser);
    private readonly pbc::RepeatedField<global::Game.Protocal.SCStealResult> stealResult_ = new pbc::RepeatedField<global::Game.Protocal.SCStealResult>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Game.Protocal.SCStealResult> StealResult {
      get { return stealResult_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SCStealManorGuidance);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SCStealManorGuidance other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!stealResult_.Equals(other.stealResult_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= stealResult_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      stealResult_.WriteTo(output, _repeated_stealResult_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += stealResult_.CalculateSize(_repeated_stealResult_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SCStealManorGuidance other) {
      if (other == null) {
        return;
      }
      stealResult_.Add(other.stealResult_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            stealResult_.AddEntriesFrom(input, _repeated_stealResult_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
