// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Mail.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Game.Protocal {

  /// <summary>Holder for reflection information generated from Mail.proto</summary>
  public static partial class MailReflection {

    #region Descriptor
    /// <summary>File descriptor for Mail.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MailReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpNYWlsLnByb3RvEg1HYW1lLlByb3RvY2FsIrIBCgxDU01haWxTdHJ1Y3QS",
            "DgoGTWFpbElkGAEgASgFEhAKCENvbmZpZ0lkGAIgASgFEg8KB01lc3NhZ2UY",
            "AyABKAUSDQoFVGl0bGUYBCABKAUSEQoJU3ViaGVhZElEGAUgASgFEhEKCUFk",
            "ZHJlc3NlchgGIAEoBRINCgVTdGF0ZRgHIAEoBRIUCgxEaXNhYmxlZFRpbWUY",
            "CCABKAMSFQoNSGF2ZUFjY2Vzc29yeRgJIAEoCCI3CgpTQ01haWxJbmZvEikK",
            "BE1haWwYASADKAsyGy5HYW1lLlByb3RvY2FsLkNTTWFpbFN0cnVjdCIhCg9D",
            "U0FjY2Vzc29yeUluZm8SDgoGTWFpbElkGAEgASgFIjQKD0NTTWFpbEFjY2Vz",
            "c29yeRIPCgdHb29kc0lkGAEgASgFEhAKCEdvb2RzTnVtGAIgASgFIjwKC1ND",
            "QWNjZXNzb3J5Ei0KBUdvb2RzGAEgAygLMh4uR2FtZS5Qcm90b2NhbC5DU01h",
            "aWxBY2Nlc3NvcnkiKAoWQ1NBY2Nlc3NvcnlJbldhcmVob3VzZRIOCgZNYWls",
            "SWQYASABKAUiWwoWU0NBY2Nlc3NvcnlJbldhcmVob3VzZRIOCgZNYWlsSWQY",
            "ASADKAUSMQoJR29vZHNJbmZvGAIgAygLMh4uR2FtZS5Qcm90b2NhbC5DU01h",
            "aWxBY2Nlc3NvcnkiNgoRQ1NNYWlsU3RhdGVTdHJ1Y3QSDgoGTWFpbElkGAEg",
            "ASgFEhEKCU1haWxTdGF0ZRgCIAEoBSJHChFDU0NoYW5nZU1haWxTdGF0ZRIy",
            "CghNYWlsSW5mbxgBIAMoCzIgLkdhbWUuUHJvdG9jYWwuQ1NNYWlsU3RhdGVT",
            "dHJ1Y3RiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Protocal.CSMailStruct), global::Game.Protocal.CSMailStruct.Parser, new[]{ "MailId", "ConfigId", "Message", "Title", "SubheadID", "Addresser", "State", "DisabledTime", "HaveAccessory" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Protocal.SCMailInfo), global::Game.Protocal.SCMailInfo.Parser, new[]{ "Mail" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Protocal.CSAccessoryInfo), global::Game.Protocal.CSAccessoryInfo.Parser, new[]{ "MailId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Protocal.CSMailAccessory), global::Game.Protocal.CSMailAccessory.Parser, new[]{ "GoodsId", "GoodsNum" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Protocal.SCAccessory), global::Game.Protocal.SCAccessory.Parser, new[]{ "Goods" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Protocal.CSAccessoryInWarehouse), global::Game.Protocal.CSAccessoryInWarehouse.Parser, new[]{ "MailId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Protocal.SCAccessoryInWarehouse), global::Game.Protocal.SCAccessoryInWarehouse.Parser, new[]{ "MailId", "GoodsInfo" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Protocal.CSMailStateStruct), global::Game.Protocal.CSMailStateStruct.Parser, new[]{ "MailId", "MailState" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Protocal.CSChangeMailState), global::Game.Protocal.CSChangeMailState.Parser, new[]{ "MailInfo" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 邮件结构
  /// </summary>
  public sealed partial class CSMailStruct : pb::IMessage<CSMailStruct> {
    private static readonly pb::MessageParser<CSMailStruct> _parser = new pb::MessageParser<CSMailStruct>(() => new CSMailStruct());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CSMailStruct> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Protocal.MailReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSMailStruct() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSMailStruct(CSMailStruct other) : this() {
      mailId_ = other.mailId_;
      configId_ = other.configId_;
      message_ = other.message_;
      title_ = other.title_;
      subheadID_ = other.subheadID_;
      addresser_ = other.addresser_;
      state_ = other.state_;
      disabledTime_ = other.disabledTime_;
      haveAccessory_ = other.haveAccessory_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSMailStruct Clone() {
      return new CSMailStruct(this);
    }

    /// <summary>Field number for the "MailId" field.</summary>
    public const int MailIdFieldNumber = 1;
    private int mailId_;
    /// <summary>
    /// 邮件id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MailId {
      get { return mailId_; }
      set {
        mailId_ = value;
      }
    }

    /// <summary>Field number for the "ConfigId" field.</summary>
    public const int ConfigIdFieldNumber = 2;
    private int configId_;
    /// <summary>
    /// 配置id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ConfigId {
      get { return configId_; }
      set {
        configId_ = value;
      }
    }

    /// <summary>Field number for the "Message" field.</summary>
    public const int MessageFieldNumber = 3;
    private int message_;
    /// <summary>
    /// 正文
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Message {
      get { return message_; }
      set {
        message_ = value;
      }
    }

    /// <summary>Field number for the "Title" field.</summary>
    public const int TitleFieldNumber = 4;
    private int title_;
    /// <summary>
    /// 标题
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Title {
      get { return title_; }
      set {
        title_ = value;
      }
    }

    /// <summary>Field number for the "SubheadID" field.</summary>
    public const int SubheadIDFieldNumber = 5;
    private int subheadID_;
    /// <summary>
    /// 副标题多语言ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SubheadID {
      get { return subheadID_; }
      set {
        subheadID_ = value;
      }
    }

    /// <summary>Field number for the "Addresser" field.</summary>
    public const int AddresserFieldNumber = 6;
    private int addresser_;
    /// <summary>
    /// 发件人
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Addresser {
      get { return addresser_; }
      set {
        addresser_ = value;
      }
    }

    /// <summary>Field number for the "State" field.</summary>
    public const int StateFieldNumber = 7;
    private int state_;
    /// <summary>
    /// 状态
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "DisabledTime" field.</summary>
    public const int DisabledTimeFieldNumber = 8;
    private long disabledTime_;
    /// <summary>
    /// 失效时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long DisabledTime {
      get { return disabledTime_; }
      set {
        disabledTime_ = value;
      }
    }

    /// <summary>Field number for the "HaveAccessory" field.</summary>
    public const int HaveAccessoryFieldNumber = 9;
    private bool haveAccessory_;
    /// <summary>
    /// 有无附件
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HaveAccessory {
      get { return haveAccessory_; }
      set {
        haveAccessory_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CSMailStruct);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CSMailStruct other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MailId != other.MailId) return false;
      if (ConfigId != other.ConfigId) return false;
      if (Message != other.Message) return false;
      if (Title != other.Title) return false;
      if (SubheadID != other.SubheadID) return false;
      if (Addresser != other.Addresser) return false;
      if (State != other.State) return false;
      if (DisabledTime != other.DisabledTime) return false;
      if (HaveAccessory != other.HaveAccessory) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MailId != 0) hash ^= MailId.GetHashCode();
      if (ConfigId != 0) hash ^= ConfigId.GetHashCode();
      if (Message != 0) hash ^= Message.GetHashCode();
      if (Title != 0) hash ^= Title.GetHashCode();
      if (SubheadID != 0) hash ^= SubheadID.GetHashCode();
      if (Addresser != 0) hash ^= Addresser.GetHashCode();
      if (State != 0) hash ^= State.GetHashCode();
      if (DisabledTime != 0L) hash ^= DisabledTime.GetHashCode();
      if (HaveAccessory != false) hash ^= HaveAccessory.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MailId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MailId);
      }
      if (ConfigId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ConfigId);
      }
      if (Message != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Message);
      }
      if (Title != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Title);
      }
      if (SubheadID != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(SubheadID);
      }
      if (Addresser != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Addresser);
      }
      if (State != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(State);
      }
      if (DisabledTime != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(DisabledTime);
      }
      if (HaveAccessory != false) {
        output.WriteRawTag(72);
        output.WriteBool(HaveAccessory);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MailId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MailId);
      }
      if (ConfigId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ConfigId);
      }
      if (Message != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Message);
      }
      if (Title != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Title);
      }
      if (SubheadID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SubheadID);
      }
      if (Addresser != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Addresser);
      }
      if (State != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(State);
      }
      if (DisabledTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DisabledTime);
      }
      if (HaveAccessory != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CSMailStruct other) {
      if (other == null) {
        return;
      }
      if (other.MailId != 0) {
        MailId = other.MailId;
      }
      if (other.ConfigId != 0) {
        ConfigId = other.ConfigId;
      }
      if (other.Message != 0) {
        Message = other.Message;
      }
      if (other.Title != 0) {
        Title = other.Title;
      }
      if (other.SubheadID != 0) {
        SubheadID = other.SubheadID;
      }
      if (other.Addresser != 0) {
        Addresser = other.Addresser;
      }
      if (other.State != 0) {
        State = other.State;
      }
      if (other.DisabledTime != 0L) {
        DisabledTime = other.DisabledTime;
      }
      if (other.HaveAccessory != false) {
        HaveAccessory = other.HaveAccessory;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MailId = input.ReadInt32();
            break;
          }
          case 16: {
            ConfigId = input.ReadInt32();
            break;
          }
          case 24: {
            Message = input.ReadInt32();
            break;
          }
          case 32: {
            Title = input.ReadInt32();
            break;
          }
          case 40: {
            SubheadID = input.ReadInt32();
            break;
          }
          case 48: {
            Addresser = input.ReadInt32();
            break;
          }
          case 56: {
            State = input.ReadInt32();
            break;
          }
          case 64: {
            DisabledTime = input.ReadInt64();
            break;
          }
          case 72: {
            HaveAccessory = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 获取邮件信息
  /// </summary>
  public sealed partial class SCMailInfo : pb::IMessage<SCMailInfo> {
    private static readonly pb::MessageParser<SCMailInfo> _parser = new pb::MessageParser<SCMailInfo>(() => new SCMailInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SCMailInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Protocal.MailReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCMailInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCMailInfo(SCMailInfo other) : this() {
      mail_ = other.mail_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCMailInfo Clone() {
      return new SCMailInfo(this);
    }

    /// <summary>Field number for the "Mail" field.</summary>
    public const int MailFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Game.Protocal.CSMailStruct> _repeated_mail_codec
        = pb::FieldCodec.ForMessage(10, global::Game.Protocal.CSMailStruct.Parser);
    private readonly pbc::RepeatedField<global::Game.Protocal.CSMailStruct> mail_ = new pbc::RepeatedField<global::Game.Protocal.CSMailStruct>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Game.Protocal.CSMailStruct> Mail {
      get { return mail_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SCMailInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SCMailInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!mail_.Equals(other.mail_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= mail_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      mail_.WriteTo(output, _repeated_mail_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += mail_.CalculateSize(_repeated_mail_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SCMailInfo other) {
      if (other == null) {
        return;
      }
      mail_.Add(other.mail_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            mail_.AddEntriesFrom(input, _repeated_mail_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 获取附件信息
  /// </summary>
  public sealed partial class CSAccessoryInfo : pb::IMessage<CSAccessoryInfo> {
    private static readonly pb::MessageParser<CSAccessoryInfo> _parser = new pb::MessageParser<CSAccessoryInfo>(() => new CSAccessoryInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CSAccessoryInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Protocal.MailReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSAccessoryInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSAccessoryInfo(CSAccessoryInfo other) : this() {
      mailId_ = other.mailId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSAccessoryInfo Clone() {
      return new CSAccessoryInfo(this);
    }

    /// <summary>Field number for the "MailId" field.</summary>
    public const int MailIdFieldNumber = 1;
    private int mailId_;
    /// <summary>
    /// 邮件id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MailId {
      get { return mailId_; }
      set {
        mailId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CSAccessoryInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CSAccessoryInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MailId != other.MailId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MailId != 0) hash ^= MailId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MailId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MailId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MailId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MailId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CSAccessoryInfo other) {
      if (other == null) {
        return;
      }
      if (other.MailId != 0) {
        MailId = other.MailId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MailId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 邮件附件结构
  /// </summary>
  public sealed partial class CSMailAccessory : pb::IMessage<CSMailAccessory> {
    private static readonly pb::MessageParser<CSMailAccessory> _parser = new pb::MessageParser<CSMailAccessory>(() => new CSMailAccessory());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CSMailAccessory> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Protocal.MailReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSMailAccessory() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSMailAccessory(CSMailAccessory other) : this() {
      goodsId_ = other.goodsId_;
      goodsNum_ = other.goodsNum_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSMailAccessory Clone() {
      return new CSMailAccessory(this);
    }

    /// <summary>Field number for the "GoodsId" field.</summary>
    public const int GoodsIdFieldNumber = 1;
    private int goodsId_;
    /// <summary>
    /// 道具id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GoodsId {
      get { return goodsId_; }
      set {
        goodsId_ = value;
      }
    }

    /// <summary>Field number for the "GoodsNum" field.</summary>
    public const int GoodsNumFieldNumber = 2;
    private int goodsNum_;
    /// <summary>
    /// 道具数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GoodsNum {
      get { return goodsNum_; }
      set {
        goodsNum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CSMailAccessory);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CSMailAccessory other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GoodsId != other.GoodsId) return false;
      if (GoodsNum != other.GoodsNum) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (GoodsId != 0) hash ^= GoodsId.GetHashCode();
      if (GoodsNum != 0) hash ^= GoodsNum.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (GoodsId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GoodsId);
      }
      if (GoodsNum != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GoodsNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GoodsId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoodsId);
      }
      if (GoodsNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoodsNum);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CSMailAccessory other) {
      if (other == null) {
        return;
      }
      if (other.GoodsId != 0) {
        GoodsId = other.GoodsId;
      }
      if (other.GoodsNum != 0) {
        GoodsNum = other.GoodsNum;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GoodsId = input.ReadInt32();
            break;
          }
          case 16: {
            GoodsNum = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 返回附件信息
  /// </summary>
  public sealed partial class SCAccessory : pb::IMessage<SCAccessory> {
    private static readonly pb::MessageParser<SCAccessory> _parser = new pb::MessageParser<SCAccessory>(() => new SCAccessory());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SCAccessory> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Protocal.MailReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCAccessory() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCAccessory(SCAccessory other) : this() {
      goods_ = other.goods_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCAccessory Clone() {
      return new SCAccessory(this);
    }

    /// <summary>Field number for the "Goods" field.</summary>
    public const int GoodsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Game.Protocal.CSMailAccessory> _repeated_goods_codec
        = pb::FieldCodec.ForMessage(10, global::Game.Protocal.CSMailAccessory.Parser);
    private readonly pbc::RepeatedField<global::Game.Protocal.CSMailAccessory> goods_ = new pbc::RepeatedField<global::Game.Protocal.CSMailAccessory>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Game.Protocal.CSMailAccessory> Goods {
      get { return goods_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SCAccessory);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SCAccessory other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!goods_.Equals(other.goods_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= goods_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      goods_.WriteTo(output, _repeated_goods_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += goods_.CalculateSize(_repeated_goods_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SCAccessory other) {
      if (other == null) {
        return;
      }
      goods_.Add(other.goods_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            goods_.AddEntriesFrom(input, _repeated_goods_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 附件入库
  /// </summary>
  public sealed partial class CSAccessoryInWarehouse : pb::IMessage<CSAccessoryInWarehouse> {
    private static readonly pb::MessageParser<CSAccessoryInWarehouse> _parser = new pb::MessageParser<CSAccessoryInWarehouse>(() => new CSAccessoryInWarehouse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CSAccessoryInWarehouse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Protocal.MailReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSAccessoryInWarehouse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSAccessoryInWarehouse(CSAccessoryInWarehouse other) : this() {
      mailId_ = other.mailId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSAccessoryInWarehouse Clone() {
      return new CSAccessoryInWarehouse(this);
    }

    /// <summary>Field number for the "MailId" field.</summary>
    public const int MailIdFieldNumber = 1;
    private int mailId_;
    /// <summary>
    /// 邮件id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MailId {
      get { return mailId_; }
      set {
        mailId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CSAccessoryInWarehouse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CSAccessoryInWarehouse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MailId != other.MailId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MailId != 0) hash ^= MailId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MailId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MailId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MailId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MailId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CSAccessoryInWarehouse other) {
      if (other == null) {
        return;
      }
      if (other.MailId != 0) {
        MailId = other.MailId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MailId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 附件入库返回
  /// </summary>
  public sealed partial class SCAccessoryInWarehouse : pb::IMessage<SCAccessoryInWarehouse> {
    private static readonly pb::MessageParser<SCAccessoryInWarehouse> _parser = new pb::MessageParser<SCAccessoryInWarehouse>(() => new SCAccessoryInWarehouse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SCAccessoryInWarehouse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Protocal.MailReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCAccessoryInWarehouse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCAccessoryInWarehouse(SCAccessoryInWarehouse other) : this() {
      mailId_ = other.mailId_.Clone();
      goodsInfo_ = other.goodsInfo_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SCAccessoryInWarehouse Clone() {
      return new SCAccessoryInWarehouse(this);
    }

    /// <summary>Field number for the "MailId" field.</summary>
    public const int MailIdFieldNumber = 1;
    private static readonly pb::FieldCodec<int> _repeated_mailId_codec
        = pb::FieldCodec.ForInt32(10);
    private readonly pbc::RepeatedField<int> mailId_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// 邮件id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> MailId {
      get { return mailId_; }
    }

    /// <summary>Field number for the "GoodsInfo" field.</summary>
    public const int GoodsInfoFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Game.Protocal.CSMailAccessory> _repeated_goodsInfo_codec
        = pb::FieldCodec.ForMessage(18, global::Game.Protocal.CSMailAccessory.Parser);
    private readonly pbc::RepeatedField<global::Game.Protocal.CSMailAccessory> goodsInfo_ = new pbc::RepeatedField<global::Game.Protocal.CSMailAccessory>();
    /// <summary>
    /// 附件信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Game.Protocal.CSMailAccessory> GoodsInfo {
      get { return goodsInfo_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SCAccessoryInWarehouse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SCAccessoryInWarehouse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!mailId_.Equals(other.mailId_)) return false;
      if(!goodsInfo_.Equals(other.goodsInfo_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= mailId_.GetHashCode();
      hash ^= goodsInfo_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      mailId_.WriteTo(output, _repeated_mailId_codec);
      goodsInfo_.WriteTo(output, _repeated_goodsInfo_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += mailId_.CalculateSize(_repeated_mailId_codec);
      size += goodsInfo_.CalculateSize(_repeated_goodsInfo_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SCAccessoryInWarehouse other) {
      if (other == null) {
        return;
      }
      mailId_.Add(other.mailId_);
      goodsInfo_.Add(other.goodsInfo_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            mailId_.AddEntriesFrom(input, _repeated_mailId_codec);
            break;
          }
          case 18: {
            goodsInfo_.AddEntriesFrom(input, _repeated_goodsInfo_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 邮件状态结构
  /// </summary>
  public sealed partial class CSMailStateStruct : pb::IMessage<CSMailStateStruct> {
    private static readonly pb::MessageParser<CSMailStateStruct> _parser = new pb::MessageParser<CSMailStateStruct>(() => new CSMailStateStruct());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CSMailStateStruct> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Protocal.MailReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSMailStateStruct() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSMailStateStruct(CSMailStateStruct other) : this() {
      mailId_ = other.mailId_;
      mailState_ = other.mailState_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSMailStateStruct Clone() {
      return new CSMailStateStruct(this);
    }

    /// <summary>Field number for the "MailId" field.</summary>
    public const int MailIdFieldNumber = 1;
    private int mailId_;
    /// <summary>
    /// 邮件id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MailId {
      get { return mailId_; }
      set {
        mailId_ = value;
      }
    }

    /// <summary>Field number for the "MailState" field.</summary>
    public const int MailStateFieldNumber = 2;
    private int mailState_;
    /// <summary>
    /// 邮件状态
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MailState {
      get { return mailState_; }
      set {
        mailState_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CSMailStateStruct);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CSMailStateStruct other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MailId != other.MailId) return false;
      if (MailState != other.MailState) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MailId != 0) hash ^= MailId.GetHashCode();
      if (MailState != 0) hash ^= MailState.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MailId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MailId);
      }
      if (MailState != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(MailState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MailId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MailId);
      }
      if (MailState != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MailState);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CSMailStateStruct other) {
      if (other == null) {
        return;
      }
      if (other.MailId != 0) {
        MailId = other.MailId;
      }
      if (other.MailState != 0) {
        MailState = other.MailState;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MailId = input.ReadInt32();
            break;
          }
          case 16: {
            MailState = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 改变邮件状态
  /// </summary>
  public sealed partial class CSChangeMailState : pb::IMessage<CSChangeMailState> {
    private static readonly pb::MessageParser<CSChangeMailState> _parser = new pb::MessageParser<CSChangeMailState>(() => new CSChangeMailState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CSChangeMailState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Protocal.MailReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSChangeMailState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSChangeMailState(CSChangeMailState other) : this() {
      mailInfo_ = other.mailInfo_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSChangeMailState Clone() {
      return new CSChangeMailState(this);
    }

    /// <summary>Field number for the "MailInfo" field.</summary>
    public const int MailInfoFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Game.Protocal.CSMailStateStruct> _repeated_mailInfo_codec
        = pb::FieldCodec.ForMessage(10, global::Game.Protocal.CSMailStateStruct.Parser);
    private readonly pbc::RepeatedField<global::Game.Protocal.CSMailStateStruct> mailInfo_ = new pbc::RepeatedField<global::Game.Protocal.CSMailStateStruct>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Game.Protocal.CSMailStateStruct> MailInfo {
      get { return mailInfo_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CSChangeMailState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CSChangeMailState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!mailInfo_.Equals(other.mailInfo_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= mailInfo_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      mailInfo_.WriteTo(output, _repeated_mailInfo_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += mailInfo_.CalculateSize(_repeated_mailInfo_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CSChangeMailState other) {
      if (other == null) {
        return;
      }
      mailInfo_.Add(other.mailInfo_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            mailInfo_.AddEntriesFrom(input, _repeated_mailInfo_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
